'use strict';
const $=s=>document.querySelector(s);
function showView(id){document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==id);document.querySelectorAll('.nav').forEach(b=>{b.classList.toggle('active',b.dataset.view===id);b.setAttribute('aria-current',b.dataset.view===id?'page':'false')});location.hash=id;if(id==='lab')drawLab();}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$('#tour').onclick=()=>$('#tour-dialog').showModal();$('#close-tour').onclick=()=>$('#tour-dialog').close();$('#start-tour').onclick=()=>{$('#tour-dialog').close();showView('studio')};
$('#fullscreen').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{$('#fullscreen').textContent='请按 F11 全屏'}};
const topics=CURRICULUM.map(t=>({...t,heading:t.title,source:`《${t.book==='phy'?'物理光学':'光电子学'}》 · ${t.ref}`,lines:t.ranges.map(r=>r.join('–')).join('、'),file:t.book==='phy'?'物理光学_教材.md':'光电子学.md'}));
function ask(q,topicId){q=q.trim();if(!q)return;const user=document.createElement('div');user.className='message user';user.textContent=q;$('#chat').append(user);const scored=topics.map(t=>({t,score:t.keys.reduce((s,k)=>s+(q.toLowerCase().includes(k)?k.length:0),0)})).sort((a,b)=>b.score-a.score);const t=topicId?topics.find(t=>t.id===topicId):(scored[0].score?scored[0].t:null);const msg=document.createElement('div');msg.className='message assistant';if(t){msg.innerHTML=`<span class="message-label">教材匹配 / 离线讲解示例</span><h3>${t.heading}</h3><p>${t.answer}</p><div class="answer-formula">${t.formula}</div><p>${t.detail}</p><button class="answer-link" data-source="${t.id}">查看教材依据 ↗</button>${t.lab?`<button class="answer-link" data-lab="${t.lab}">去配套实验验证 →</button>`:''}<button class="answer-link" data-lesson="${t.id}">查看详细课堂讲稿 →</button>`;updateSource(t)}else{msg.innerHTML='<span class="message-label">材料范围提示</span><h3>当前片段不足以回答这个问题。</h3><p>本离线示例提供 14 个章节主题的预置讲解。请从上方章节目录选择最接近的主题；超出这些片段的细节仍需补充材料。</p>';$('#source-preview').textContent='未匹配到教材片段。请使用已有主题，避免把无依据的内容当作答案。'}$('#chat').append(msg);$('#chat').scrollTop=$('#chat').scrollHeight;$('#question').value=''}
function updateSource(t){$('#source-preview').innerHTML=`<b>已匹配 · ${t.title}</b><p>${t.source}</p><blockquote>${t.quote}</blockquote><span>教材整理稿摘录 · ${t.file}<br>原整理稿行号 ${t.lines}。本页解释为教学改写；OCR 整理稿可能有误，正式引用请核对原 PDF。</span><a href="sources/${t.id}.txt" target="_blank" rel="noopener">打开随站保存的来源片段 ↗</a>`}
$('#ask-form').onsubmit=e=>{e.preventDefault();ask($('#question').value)};document.addEventListener('click',e=>{const q=e.target.closest('[data-question]');if(q)ask(q.dataset.question);const s=e.target.closest('[data-source]');if(s)updateSource(topics.find(t=>t.id===s.dataset.source));const lb=e.target.closest('[data-lab]');if(lb)window.openExperiment(lb.dataset.lab);const lp=e.target.closest('[data-lesson]');if(lp){$('#lesson-topic').value=lp.dataset.lesson;generatePlan();showView('teacher')}});
let rotation=null;
function drawLab(){
 const deg=Number($('#angle').value),a=deg*Math.PI/180,f=Math.cos(a)**2;
 $('#angle-value').textContent=deg;$('#intensity').innerHTML=(100*f).toFixed(1)+'<small>%</small>';
 $('#lab-explain').textContent=deg===90?'两方向正交，电场投影为零，因此理想透射光强为零。实际器件可能仍有微弱漏光。':deg===0||deg===180?'透光轴与入射偏振方向共线，光强达到最大。180° 时电场投影的符号改变，但平方后的光强不变。':`电场投影的大小为原振幅的 ${Math.abs(Math.cos(a)).toFixed(3)} 倍；平方后，透射光强为原来的 ${(f*100).toFixed(1)}%。`;
 const c=$('#optics'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#102631';ctx.fillRect(0,0,w,h);
 ctx.strokeStyle='#23404c';ctx.lineWidth=1;for(let x=0;x<w;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
 const cy=228;ctx.setLineDash([7,8]);ctx.strokeStyle='#49616c';ctx.beginPath();ctx.moveTo(50,cy);ctx.lineTo(1040,cy);ctx.stroke();ctx.setLineDash([]);
 const beam=(x1,x2,alpha)=>{const grad=ctx.createLinearGradient(0,cy-44,0,cy+44);grad.addColorStop(0,`rgba(80,230,183,0)`);grad.addColorStop(.5,`rgba(80,230,183,${alpha})`);grad.addColorStop(1,`rgba(80,230,183,0)`);ctx.fillStyle=grad;ctx.fillRect(x1,cy-44,x2-x1,88);ctx.strokeStyle=`rgba(142,255,220,${alpha+.05})`;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x1,cy);ctx.lineTo(x2,cy);ctx.stroke()};beam(125,530,.45);beam(578,957,f*.6);
 ctx.fillStyle='#2b4552';ctx.fillRect(52,cy-35,84,70);ctx.fillStyle='#405e6b';ctx.fillRect(124,cy-22,18,44);
 const polarizer=(x,angle)=>{ctx.save();ctx.translate(x,cy);ctx.fillStyle='#214c54dd';ctx.strokeStyle='#79c6b2';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,0,53,124,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.save();ctx.beginPath();ctx.ellipse(0,0,50,121,0,0,Math.PI*2);ctx.clip();ctx.rotate(angle);ctx.strokeStyle='#74c0b288';ctx.lineWidth=2;for(let j=-120;j<140;j+=13){ctx.beginPath();ctx.moveTo(j,-150);ctx.lineTo(j,150);ctx.stroke()}ctx.strokeStyle='#c7ffed';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,-104);ctx.lineTo(0,104);ctx.stroke();ctx.restore();ctx.strokeStyle='#77939e';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(0,125);ctx.lineTo(0,151);ctx.stroke();ctx.fillStyle='#365662';ctx.fillRect(-43,148,86,8);ctx.restore()};polarizer(320,0);polarizer(554,-a);
 for(let x=185;x<300;x+=38){ctx.strokeStyle='#8ee5c7';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,cy-36);ctx.lineTo(x,cy+36);ctx.stroke()}
 ctx.fillStyle='#344b5a';ctx.fillRect(942,100,95,250);ctx.fillStyle='#101f29';ctx.fillRect(950,108,79,234);const glow=ctx.createRadialGradient(989,cy,2,989,cy,75);glow.addColorStop(0,`rgba(158,255,210,${f})`);glow.addColorStop(.4,`rgba(57,239,165,${f*.85})`);glow.addColorStop(1,'rgba(57,239,165,0)');ctx.fillStyle=glow;ctx.fillRect(950,108,79,234);
 ctx.font='18px "Microsoft YaHei", sans-serif';ctx.fillStyle='#b5ced5';ctx.textAlign='center';ctx.fillText('线偏振光源',100,65);ctx.fillText('入射偏振方向',320,65);ctx.fillText('检偏器',554,65);ctx.fillText('探测屏',990,65);ctx.fillStyle='#8ae4c8';ctx.font='24px Georgia';ctx.fillText(`θ = ${deg}°`,554,410);ctx.fillText(`I / I₀ = ${f.toFixed(3)}`,795,330);ctx.font='16px "Microsoft YaHei", sans-serif';ctx.fillStyle='#7799a8';ctx.fillText('结构示意，非光线追迹',830,408);
}
$('#angle').oninput=drawLab;document.querySelectorAll('[data-angle]').forEach(b=>b.onclick=()=>{$('#angle').value=b.dataset.angle;drawLab()});$('#animate').onclick=()=>{if(rotation){clearInterval(rotation);rotation=null;$('#animate').textContent='▷ 自动旋转'}else{$('#animate').textContent='Ⅱ 暂停旋转';rotation=setInterval(()=>{$('#angle').value=(Number($('#angle').value)+1)%181;drawLab()},55)}};
const quizzes=[
 {q:'线偏振光通过理想检偏器，夹角为 45°。透射光强是入射光强的多少？',options:['50%','70.7%','25%','0%'],correct:0,explain:'振幅取 cos45° ≈ 0.707，光强取其平方，所以 I / I₀ = 0.5。',errors:['','把振幅比 cosθ 直接当成了光强比。','题目已说明入射光为线偏振光，无需再乘起偏器的 1/2。','只有透光轴与入射偏振方向正交时才理想消光。'],follow:'先问“电场振幅变为多少”，再问“探测器测量的是振幅还是光强”。',action:'回到实验台，比较 0°、45°、90° 三个角度。'},
 {q:'理想透明介质界面发生全反射时，第二介质中的电磁场如何？',options:['处处为零','界面附近存在衰减的倏逝场','与入射场完全相同','一定有向深处传播的折射光'],correct:1,explain:'全反射时第二介质中仍存在倏逝场。在理想单界面模型中，法向净时间平均能流为零不等于场为零。',errors:['把“无透射净能流”等同于“没有电磁场”。','','没有考虑界面边界条件与场的空间变化。','将传播波与指数衰减的倏逝场混为一谈。'],follow:'如果界面另一侧的场突然为零，切向电场的连续条件还能满足吗？',action:'让学生分别表述“场是否存在”与“能量是否净穿过界面”。'},
 {q:'自然光以布儒斯特角入射理想透明电介质界面，反射光有什么特征？',options:['只有 p 偏振分量','没有任何反射光','只有 s 偏振分量','反射光仍是自然光'],correct:2,explain:'布儒斯特角处 p 偏振反射系数为零，反射光只含 s 偏振。透射光一般仍有两种分量。',errors:['把 s、p 偏振方向或消失的分量记反了。','p 分量不反射，不代表 s 分量也不反射。','','忽略了界面对两种偏振的反射率不同。'],follow:'先画出入射面，再分别标出 s 与 p 的电场方向。',action:'追问：反射光完全偏振，是否意味着透射光也完全偏振？'}
];let quizIndex=0,chosen=null,submitted=false;
function renderQuiz(){const q=quizzes[quizIndex];chosen=null;submitted=false;$('#quiz-count').textContent=`0${quizIndex+1} / 03`;$('#quiz-question').textContent=q.q;$('#quiz-options').innerHTML=q.options.map((o,i)=>`<button class="quiz-option" data-option="${i}" aria-pressed="false"><span>${'ABCD'[i]}</span>${o}</button>`).join('');$('#quiz-feedback').innerHTML='';$('#submit-quiz').disabled=false;$('#diagnosis-body').innerHTML='<div class="empty-symbol">◎</div><h3>等待这道题的作答</h3><p class="muted">根据所选答案，定位一个值得继续追问的概念。</p>';document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{if(submitted)return;chosen=Number(b.dataset.option);document.querySelectorAll('[data-option]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',x===b?'true':'false')})})}
$('#submit-quiz').onclick=()=>{if(chosen===null){$('#quiz-feedback').textContent='请先选择一个答案。';return}submitted=true;const q=quizzes[quizIndex],ok=chosen===q.correct;document.querySelectorAll('[data-option]').forEach(b=>{const i=Number(b.dataset.option);b.classList.toggle('correct',i===q.correct);b.classList.toggle('wrong',i===chosen&&!ok);b.disabled=true});$('#submit-quiz').disabled=true;$('#quiz-feedback').innerHTML=`<div class="feedback ${ok?'':'wrong'}"><b>${ok?'理解正确，继续追问一步。':'这个错误，正好能帮我们定位问题。'}</b><p>${q.explain}</p></div>`;$('#diagnosis-body').innerHTML=`<span class="diagnostic-label">本次作答 / ${'ABCD'[chosen]}</span><h3>${ok?'已掌握当前判断':q.errors[chosen]}</h3><span class="diagnostic-label">建议教师追问</span><p>${q.follow}</p><span class="diagnostic-label">下一步课堂动作</span><p>${q.action}</p><button class="answer-link" id="quiz-to-lab">${quizIndex===0?'打开实验台 →':'返回知识库 →'}</button>`;$('#quiz-to-lab').onclick=()=>{if(quizIndex===0)window.openExperiment('polar');else showView('knowledge')}};$('#next-quiz').onclick=()=>{quizIndex=(quizIndex+1)%quizzes.length;renderQuiz()};
let currentPlan='';
function generatePlan(){renderLesson();}
$('#generate-plan').onclick=generatePlan;$('#export-plan').onclick=()=>{const blob=new Blob(['\ufeff'+currentPlan],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='光知-课堂活动讲稿.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(['atlas','studio','library','knowledge','lab','quiz','teacher'].includes(id))showView(id)});
renderQuiz();drawLab();
showView(['atlas','studio','library','knowledge','lab','quiz','teacher'].includes(location.hash.slice(1))?location.hash.slice(1):'atlas');
