(()=>{'use strict';const q=s=>document.querySelector(s),qa=s=>Array.from(document.querySelectorAll(s)),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const demos={
1:{title:'光电系统的四个环节',question:'手机、光纤通信和激光雷达，共用哪些基础环节？',intuition:'把复杂系统拆成“产生光 → 传输光 → 调控光 → 探测光”。教材各章分别解释一个环节，最后再把它们接回系统。',equation:'光源 → 波导 → 调制器 → 探测器',answer:'激光器负责产生光，光纤负责传输，调制器把信息写入光，探测器把光转回电信号。器件不同，这条信息链仍可以作为分析起点。',param:'信号流动速度',min:1,max:5,step:1,value:2,boundary:'系统关系示意；动画速度仅用于展示，不代表器件带宽或真实光速。',search:'光电子学',link:'photon'},
2:{title:'束腰与传播包络',question:'为什么更小的光斑，未必能传播得更远？',intuition:'束腰描述横向集中程度，发散角描述传播方向的展开程度。固定波长时，二者不能同时任意变小。',equation:'θ₀ = λ/(πW₀)；z₀ = πW₀²/λ',answer:'束腰减半，远场半发散角变为两倍，瑞利长度与焦深变为四分之一。这里使用空气中的理想基模高斯光束。',param:'束腰半径 W₀',min:50,max:200,step:1,value:100,boundary:'λ = 633 nm，M² = 1，近轴基模；边界为 1/e² 强度半径，横纵尺度不同。',search:'高斯光束',lab:'gaussian',link:'gaussian',studio:true},
3:{title:'光纤的接收锥与光线路径',question:'照进光纤端面的光，都能被导引吗？',intuition:'入射角改变光在芯层中的传播方向。只有满足芯包界面全反射条件的一部分方向，才属于光纤的接收范围。',equation:'NA = √(n₁² − n₂²) = sin θₐ',answer:'对于本例 n₁ = 1.45、n₂ = 1.444，空气中的最大接收半角约为 7.57°。接收条件与单模条件是两件事，单模还要看 V 参数。',param:'空气中入射半角',min:0,max:20,step:.1,value:5,boundary:'空气入射、阶跃折射率、子午光线；结构和光线路径采用不同比例，不模拟模式干涉。',search:'数值孔径',lab:'fiber',link:'fiber'},
4:{title:'同样的光功率，有多少个光子？',question:'功率相同，红外光的光子数会比可见光多吗？',intuition:'功率是每秒输送的总能量。长波长对应更小的单光子能量，因此同样的功率需要更多的光子。',equation:'E = hc/λ；Φ = P/E',answer:'会更多。固定功率时，光子通量与波长成正比。例如波长翻倍，单光子能量减半，平均光子通量加倍。',param:'波长 λ',min:400,max:1600,step:10,value:633,boundary:'P = 1 mW；粒子数只表示通量变化趋势，屏幕上每个亮点不对应一个实际光子，不模拟量子统计。',search:'光子通量',lab:'detector',link:'photon'},
5:{title:'跨过阈值，激光开始振荡',question:'为什么泵浦能量增加，激光输出并非从零一直线性增加？',intuition:'泵浦先建立反转。达到振荡阈值后，受激放大足以补偿腔损耗，激光输出才进入近似线性增长区。',equation:'示例：Pout = ηs · max(Ppump − Pth, 0)',answer:'阈值由增益与损耗共同决定。本图阈值设为 40 mW，斜率效率为 0.35；这两个数值用于教学，不是特定激光器实测参数。',param:'泵浦功率',min:0,max:120,step:1,value:65,boundary:'简化稳态阈值模型；忽略阈下自发辐射背景、热效应和饱和，仅示意激光分量。',search:'激光阈值',link:'threshold'},
6:{title:'带隙是一道能量门槛',question:'为什么某些材料对特定波长的光很难发生带间吸收？',intuition:'电子从价带跃迁到导带需要足够的能量。先比较单光子能量与带隙，再考虑跃迁概率和材料具体结构。',equation:'hν ≥ Eg；λg ≈ 1240/Eg（nm）',answer:'本例入射光为 850 nm，光子能量约 1.46 eV。带隙大于这一能量时，理想单光子带间跃迁能量不足；满足门槛也不保证高吸收率。',param:'带隙 Eg',min:70,max:300,step:1,value:112,boundary:'仅比较单光子带间跃迁的能量门槛；不模拟间接带隙的声子辅助、缺陷吸收或跃迁概率。',search:'带隙波长',link:'bandgap'},
7:{title:'把光功率变成电流',question:'光电流大一倍，是光更强了，还是探测器更灵敏？',intuition:'光电流同时取决于入射光功率和响应度。固定波长与量子效率后，才可以把电流变化直接对应到光功率变化。',equation:'R = ηqλ/(hc)；Iph = R · P',answer:'在本例固定 850 nm、量子效率 0.8 时，响应度约为 0.548 A/W。100 μW 光功率产生约 54.8 μA 光生电流，功率翻倍则电流翻倍。',param:'入射光功率',min:0,max:200,step:1,value:100,boundary:'理想无内部增益探测器，λ = 850 nm、η = 0.8；忽略暗电流、噪声、带宽和饱和。',search:'光电二极管',lab:'detector',link:'detector'},
8:{title:'用电压控制透射光强',question:'电场先改变相位，为什么最后能改变亮度？',intuition:'电光晶体把电压转成两个偏振分量之间的相位差；偏振器与检偏器再把相位差转成可见的光强变化。',equation:'Δφ = πV/Vπ；I/I₀ = sin²(Δφ/2)',answer:'本例输入偏振相对晶轴为 45°，起偏器与检偏器正交。V = 0 时暗，V = Vπ 时亮，V = 2Vπ 时再次变暗；实际偏置决定工作点。',param:'电压与半波电压之比',min:0,max:200,step:1,value:100,boundary:'理想正交偏振器、45° 入射偏振、零自然相位延迟；忽略插入损耗与有限消光比。',search:'电光调制',link:'modulation'},
9:{title:'相位匹配，让新生光场相长叠加',question:'晶体更长，倍频光就一定更强吗？',intuition:'晶体各处都能产生倍频场，但能否累加取决于相位关系。相位失配时，不同位置产生的场可能部分抵消。',equation:'P₂ω ∝ L² sinc²(ΔkL/2)',answer:'在固定晶体长度、未耗尽泵浦近似下，归一化输出随相位失配振荡；当 ΔkL/2 = π 时，理想模型中恰好相消。完美匹配时相长积累。',param:'归一化失配 x = ΔkL/2',min:0,max:628,step:1,value:0,boundary:'固定 L、平面波、无损耗、未耗尽泵浦；读数是相对完美匹配输出，不是绝对转换效率。',search:'位相匹配',link:'shg'}
};
let current=1,selected=null,time=0,last=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches;
q('#atlas-topic-count').textContent=BOOK_ATLAS.topicCount;
q('#atlas-chapters').innerHTML=BOOK_ATLAS.chapters.map(c=>`<button data-atlas-chapter="${c.id}"><small>CHAPTER ${String(c.id).padStart(2,'0')}</small><b>${escape(c.title)}</b><span>${c.topics.length} 节知识点</span></button>`).join('');
function selectTopic(id){const t=BOOK_ATLAS.chapters.flatMap(c=>c.topics).find(t=>t.id===id);if(!t)return;selected=id;qa('[data-atlas-topic]').forEach(b=>b.classList.toggle('active',b.dataset.atlasTopic===id));const children=BOOK_ATLAS.chapters.flatMap(c=>c.topics).filter(x=>x.id.startsWith(id+'.'));q('#atlas-topic-reader').innerHTML=`<div class="section-kicker">TEXTBOOK ANCHOR / 原文有位置</div><h3>${t.id} ${escape(t.title)}</h3><div class="topic-location">教材印刷第 ${t.printPage} 页 · Markdown 第 ${t.start}–${t.end} 行</div><p class="topic-prose">${escape(t.preview||'本节为上级目录，继续选择下方子节阅读具体知识。')}</p><div class="atlas-concepts">${t.concepts.map(x=>`<span>${escape(x)}</span>`).join('')}${!t.preview?children.map(x=>`<button class="answer-link" data-atlas-topic="${x.id}">${escape(x.title)} →</button>`).join(''):''}</div><button class="answer-link" data-search="${escape(t.title)}">在教材与课件中继续检索 ↗</button><details><summary>展开这一节的完整 Markdown 原文</summary><pre class="source-raw">${escape(t.text||'请选择本节下的子知识点阅读原文。')}</pre></details><p class="small-note">来源：已整理《光电子学》教材。印刷页码取自教材目录；文字和公式存在 OCR 误差，正式使用请核对原书。</p>`;}
function topicList(){const filter=q('#atlas-filter').value.trim().toLowerCase(),chapter=BOOK_ATLAS.chapters[current-1];let topics=filter?BOOK_ATLAS.chapters.flatMap(c=>c.topics).filter(t=>(t.id+' '+t.title+' '+t.concepts.join(' ')).toLowerCase().includes(filter)):chapter.topics;q('#atlas-topic-list').innerHTML=(filter?`<div class="atlas-global-result">全书匹配 ${topics.length} 个知识点</div>`:'')+topics.map(t=>`<button data-atlas-topic="${t.id}" class="${t.depth===3?'subtopic':''}"><b>${t.id} ${escape(t.title)}</b><small>教材第 ${t.printPage} 页 · ${t.concepts.length?'含 '+t.concepts.length+' 个内容提示':'原文可查'}</small></button>`).join('');if(topics.length)selectTopic(topics[0].id);else{q('#atlas-topic-list').innerHTML='<div class="atlas-topics-empty">没有匹配的标题。可前往课程资料库搜索原文。</div>';q('#atlas-topic-reader').innerHTML='<h3>换一个课程关键词试试</h3><p class="small-note">此处筛选教材标题与小知识点；全文检索请打开“课程资料库”。</p>'}}
function changeChapter(n){current=+n;const c=BOOK_ATLAS.chapters[current-1],d=demos[current];qa('[data-atlas-chapter]').forEach(b=>b.classList.toggle('active',+b.dataset.atlasChapter===current));q('#atlas-chapter-number').textContent='CHAPTER '+String(current).padStart(2,'0');q('#atlas-chapter-title').textContent=c.title;q('#atlas-chapter-intro').textContent=c.intro;q('#atlas-demo-title').textContent=d.title;q('#atlas-question').textContent=d.question;q('#atlas-intuition').textContent=d.intuition;q('#atlas-equation').textContent=d.equation;q('#atlas-answer p').textContent=d.answer;q('#atlas-answer').open=false;q('#atlas-param-label').textContent=d.param;const p=q('#atlas-param');p.min=d.min;p.max=d.max;p.step=d.step;p.value=d.value;q('#atlas-boundary').textContent=d.boundary;q('#atlas-actions').innerHTML=(d.studio?'<button class="answer-link" data-atlas-studio>查看课件原页与进阶演示 →</button>':'')+(d.lab?`<button class="answer-link" data-atlas-lab="${d.lab}">进入完整实验台 →</button>`:'')+`<button class="answer-link" data-atlas-lesson="${d.link}">查看相关详细讲稿 →</button>`;q('#atlas-filter').value='';topicList();update();}
q('#atlas-filter').oninput=topicList;q('#atlas-param').oninput=update;q('#atlas-search-chapter').onclick=()=>{window.searchCourseLibrary(demos[current].search)};
document.addEventListener('click',e=>{const c=e.target.closest('[data-atlas-chapter]');if(c)changeChapter(c.dataset.atlasChapter);const t=e.target.closest('[data-atlas-topic]');if(t)selectTopic(t.dataset.atlasTopic);const l=e.target.closest('[data-atlas-lab]');if(l)window.openExperiment(l.dataset.atlasLab);const p=e.target.closest('[data-atlas-lesson]');if(p){q('#lesson-topic').value=p.dataset.atlasLesson;renderLesson();showView('teacher')}if(e.target.closest('[data-atlas-studio]')){showView('studio');q('[data-story="gaussian"]').click()}});
q('#atlas-motion').onclick=()=>{paused=!paused;q('#atlas-motion').textContent=paused?'▷ 播放':'Ⅱ 暂停'};if(paused)q('#atlas-motion').textContent='▷ 播放';
const canvas=q('#atlas-canvas'),ctx=canvas.getContext('2d');function reading(a,b){return `<div><span>${a}</span><b>${b}</b></div>`}
function update(){const v=+q('#atlas-param').value;let r='',out='';switch(current){case 1:out=v+' ×';r=reading('系统环节','产生 → 传输')+reading('信息处理','调控 → 探测')+reading('知识跨度','第 1–9 章');break;case 2:{const g=Optics.gaussian(v,633,0);out=v+' μm';r=reading('束腰半径',v+' μm')+reading('半发散角',g.divergence.toFixed(2)+' mrad')+reading('焦深',(g.zr*2).toFixed(1)+' mm');break}case 3:{const f=Optics.fiber(.006,4.1,1550,v);out=v.toFixed(1)+'°';r=reading('数值孔径',f.na.toFixed(3))+reading('最大接收半角',f.acceptance.toFixed(2)+'°')+reading('当前方向',f.accepted?'接收范围内':'接收范围外');break}case 4:{const p=AtlasModels.photon(v);out=v+' nm';r=reading('固定功率','1 mW')+reading('单光子能量',p.energyEv.toFixed(2)+' eV')+reading('光子通量',(p.flux/1e15).toFixed(2)+' ×10¹⁵/s');break}case 5:{const a=AtlasModels.laser(v);out=v+' mW';r=reading('泵浦功率',v+' mW')+reading('阈值',a.threshold+' mW')+reading('激光输出',a.power.toFixed(1)+' mW');break}case 6:{const g=AtlasModels.bandgap(v/100);out=(v/100).toFixed(2)+' eV';r=reading('入射波长','850 nm')+reading('带隙波长',g.cutoff.toFixed(0)+' nm')+reading('能量门槛',g.allowed?'满足':'不足');break}case 7:{const d=Optics.detector(850,.8,v);out=v+' μW';r=reading('响应度',d.responsivity.toFixed(3)+' A/W')+reading('光生电流',d.current.toFixed(1)+' μA')+reading('量子效率','80%');break}case 8:{const ratio=v/100;out=ratio.toFixed(2)+' Vπ';r=reading('相位延迟',ratio.toFixed(2)+' π')+reading('相对透射光强',(100*AtlasModels.modulation(ratio)).toFixed(1)+'%')+reading('器件配置','正交检偏');break}case 9:{const x=v/100;out=x.toFixed(2);r=reading('归一化失配',x.toFixed(2))+reading('相对倍频输出',(100*AtlasModels.phaseMismatch(x)).toFixed(1)+'%')+reading('完美匹配参考','100%');break}}q('#atlas-param-value').textContent=out;q('#atlas-readings').innerHTML=r;draw();}
function label(s,x,y,color='#a2c3cb',size=18,align='center'){ctx.font=`${size}px "Microsoft YaHei",sans-serif`;ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(s,x,y)}
function line(x1,y1,x2,y2,color='#4f807e',width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function dot(x,y,r=4,color='#aff9cb'){ctx.save();ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=15;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.restore()}
function box(x,y,w,h,title,subtitle){ctx.fillStyle='#173e49';ctx.strokeStyle='#467273';ctx.lineWidth=1;ctx.beginPath();ctx.roundRect(x,y,w,h,12);ctx.fill();ctx.stroke();label(title,x+w/2,y+h/2,'#d2f3e6',22);if(subtitle)label(subtitle,x+w/2,y+h/2+30,'#81a8b0',13)}
function curve(fn,maxX,maxY,color='#8beabb'){line(95,270,915,270,'#638893');line(95,270,95,55,'#638893');ctx.beginPath();for(let i=0;i<=300;i++){const x=i/300*maxX,y=fn(x);i?ctx.lineTo(95+i/300*820,270-y/maxY*190):ctx.moveTo(95,270-y/maxY*190)}ctx.strokeStyle=color;ctx.lineWidth=3;ctx.stroke()}
function draw(){ctx.fillStyle='#0c2430';ctx.fillRect(0,0,1000,340);for(let x=40;x<1000;x+=40)line(x,30,x,310,'#729c9a0a',1);for(let y=30;y<330;y+=40)line(40,y,960,y,'#729c9a0a',1);const v=+q('#atlas-param').value;
if(current===1){const items=[['产生光','激光器 / LED'],['传输光','波导 / 光纤'],['调控光','电光 / 声光'],['探测光','光电二极管']];items.forEach(([a,b],i)=>{box(65+i*235,105,170,115,a,b);if(i<3){line(236+i*235,160,299+i*235,160);for(let j=0;j<3;j++)dot(237+i*235+(time*v*27+j*20)%60,160,3)}});label('把不同章节，连接成一条信息通路',500,280,'#c8e6d7',20)}
if(current===2){const width=x=>Optics.gaussian(v,633,(x-500)/2.1).w*160;ctx.beginPath();for(let x=80;x<=920;x+=4){x===80?ctx.moveTo(x,165-width(x)):ctx.lineTo(x,165-width(x))}for(let x=920;x>=80;x-=4)ctx.lineTo(x,165+width(x));ctx.closePath();const grad=ctx.createLinearGradient(0,30,0,300);grad.addColorStop(0,'#5ae9b10a');grad.addColorStop(.5,'#5ae9b16a');grad.addColorStop(1,'#5ae9b10a');ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle='#98e8bd';ctx.lineWidth=2;ctx.stroke();for(let i=0;i<26;i++){const x=80+(time*90+i*33)%840;dot(x,165+Math.sin(i*4.7)*width(x)*.7,2)}line(500,165-width(500),500,165+width(500),'#e1edce');label('W₀',523,150-width(500),'#e1edce',18);label('−200 mm',80,310,'#87a8b3',16);label('束腰',500,310,'#87a8b3',16);label('+200 mm',920,310,'#87a8b3',16)}
if(current===3){const f=Optics.fiber(.006,4.1,1550,v),a=v*Math.PI/180;ctx.fillStyle='#31526866';ctx.fillRect(240,85,650,160);ctx.fillStyle='#2a626065';ctx.fillRect(240,120,650,90);line(240,120,890,120,'#90c6b9');line(240,210,890,210,'#90c6b9');line(95,165-Math.tan(a)*260,240,165,'#e8d299',3);if(f.accepted){const slope=Math.tan(Math.asin(Math.sin(a)/1.45))*2;let y=165,dir=1;ctx.beginPath();ctx.moveTo(240,y);for(let x=242;x<=890;x+=2){y+=dir*slope*2;if(y>210){y=420-y;dir=-1}if(y<120){y=240-y;dir=1}ctx.lineTo(x,y)}ctx.strokeStyle='#9bf4c8';ctx.lineWidth=3;ctx.stroke();}else{line(240,165,560,210,'#f1ba7d',3);line(560,210,900,295,'#f1ba7d',2)}label('芯层 n₁ = 1.450',555,165,'#d6efe5',20);label('包层 n₂ = 1.444',560,70,'#98b8c4',17);label(f.accepted?'方向满足全反射导引条件':'当前方向超出接收锥',500,320,f.accepted?'#b5ebc9':'#edbf85',19)}
if(current===4){box(55,105,155,120,'1 mW','恒定光功率');box(820,105,135,120,'计数窗','平均光子通量');line(225,165,805,165,'#35646d');const count=Math.round(v/40);for(let i=0;i<count;i++){const x=230+(time*110+i*578/count)%575;dot(x,130+(i%4)*24,3.5,'#a5f5d0')}label(v+' nm：每个光子的能量 '+AtlasModels.photon(v).energyEv.toFixed(2)+' eV',500,280,'#cae6d8',22)}
if(current===5){curve(x=>AtlasModels.laser(x).power,120,30);const x=95+v/120*820,y=270-AtlasModels.laser(v).power/30*190;line(95+40/120*820,55,95+40/120*820,270,'#d7ae7166');dot(x,y,7);label('阈值 40 mW',95+40/120*820,42,'#dbbe8b',16);label('泵浦功率 / mW',500,322,'#96b8be',16);label('激光输出 / mW',195,45,'#96b8be',16);label('0',95,295,'#70939e',14);label('120',915,295,'#70939e',14)}
if(current===6){const g=AtlasModels.bandgap(v/100),gap=v/300*155;line(390,255,830,255,'#90c0cf',4);line(390,255-gap,830,255-gap,'#90c0cf',4);label('价带',870,262,'#9bbcc5',18);label('导带',870,262-gap,'#9bbcc5',18);label('Eg = '+(v/100).toFixed(2)+' eV',625,235-gap/2,'#e1cc96',21);for(let i=0;i<5;i++)dot(440+i*65,255,5);const x=100+(time*110)%265;dot(x,200,5,'#efcb85');label('850 nm 光子',210,155,'#e2c383',19);label('E ≈ 1.46 eV',210,235,'#9bb8c5',17);if(g.allowed){const progress=(time*.65)%1;dot(570,255-progress*gap,7,'#b1f6c9');line(570,247,570,260-gap,'#7ec9ac',2)}label(g.allowed?'满足能量门槛；实际吸收还取决于跃迁概率':'能量不足，不能完成本模型中的带间跃迁',500,315,g.allowed?'#b1e7c8':'#e2b983',18)}
if(current===7){box(70,110,160,115,'入射光',v+' μW');box(400,85,195,165,'光电二极管','η = 0.8');box(760,110,170,115,Optics.detector(850,.8,v).current.toFixed(1)+' μA','光生电流');line(242,165,385,165);line(610,165,745,165);for(let i=0;i<Math.ceil(v/15);i++){dot(245+(time*100+i*17)%135,145+i%3*20,3);dot(614+(time*100+i*17)%128,165,2.5,'#f3cb86')}label('固定波长与量子效率，光功率和光生电流成正比',500,300,'#c9e6d5',19)}
if(current===8){const ratio=AtlasModels.modulation(v/100);box(60,110,135,110,'起偏器','45°');box(365,85,215,165,'电光晶体','Δφ = '+(v/100).toFixed(2)+'π');box(725,110,135,110,'检偏器','与起偏器正交');line(208,165,350,165,'#93e8bc',5);line(595,165,710,165,'#93e8bc',5);ctx.save();ctx.globalAlpha=.06+.94*ratio;line(873,165,958,165,'#aafbc5',13);dot(952,165,12);ctx.restore();label('透射光强 '+(ratio*100).toFixed(1)+'%',500,306,'#cdecd7',24)}
if(current===9){curve(x=>AtlasModels.phaseMismatch(x),Math.PI*2,1);const x=v/100;dot(95+x/(Math.PI*2)*820,270-AtlasModels.phaseMismatch(x)*190,7,'#edd08e');label('完美匹配',120,50,'#93d8ba',16);label('π',505,293,'#9cb8bf',17);label('2π',915,293,'#9cb8bf',17);label('归一化失配 ΔkL/2',505,326,'#9cb8bf',16);label('相对倍频输出',790,56,'#afcccb',17)}
}
function loop(now){const dt=last?Math.min((now-last)/1000,.05):0;last=now;if(!q('#atlas').hidden&&!paused){time+=dt;draw()}requestAnimationFrame(loop)}changeChapter(1);requestAnimationFrame(loop);
})();
