'use strict';
(() => {
 const configs={
 polar:{title:'偏振与马吕斯定律',subtitle:'先投影电场，再观察光强如何变化。',source:'基础补充 · 物理光学第十五章',topic:'polar'},
 fresnel:{title:'反射、布儒斯特角与全反射',subtitle:'改变入射方向与角度，比较 s、p 两种偏振的反射率。',source:'基础补充 · 物理光学第十一章',topic:'tir',controls:[['n1','入射介质折射率 n₁',1,2.2,.01,1],['n2','透射介质折射率 n₂',1,2.2,.01,1.5],['theta','入射角 θ₁（相对法线）',0,89.9,.01,56.31,'°']],formula:'Rₛ=|rₛ|²；Rₚ=|rₚ|²；θB=arctan(n₂/n₁)',boundary:'无吸收、非磁性、无限平面电介质界面；曲线为功率反射率。光路为示意，不是有限光束仿真。',challenge:'切换玻璃→空气，比较临界角两侧；再解释“R=1”为什么不表示第二介质的场消失。'},
 gaussian:{title:'高斯光束、束腰与焦深',subtitle:'固定波长或束腰，观察传播半径与轴上光强的变化。',source:'光电子学 · 第2章 §2.3.2',topic:'gaussian',controls:[['w0','束腰半径 W₀',20,400,1,100,'μm'],['lambda','空气中的波长 λ',400,1600,1,633,'nm'],['z','离束腰的距离 z',0,500,.01,49.63,'mm']],formula:'W(z)=W₀√[1+(z/z₀)²]；z₀=πW₀²/λ',boundary:'空气、近轴理想基模，M²=1；W 为 1/e² 光强半径，θ₀ 为远场半角；无吸收。',challenge:'把束腰从 100 μm 减半，保持 z 不变；再点“一个瑞利距离”，区分物理位置和归一化位置。'},
 cavity:{title:'球面谐振腔稳定性',subtitle:'沿用教材凹面镜 R<0 的约定，在稳定图中追踪腔参数。',source:'光电子学 · 第2章 §2.2.3',topic:'cavity',controls:[['d','腔长 d',50,2000,1,250,'mm'],['r1','凹镜 1 的 |R₁|（R₁ 取负）',100,2000,1,500,'mm'],['r2','凹镜 2 的 |R₂|（R₂ 取负）',100,2000,1,1000,'mm']],formula:'gᵢ=1+d/Rᵢ；0<g₁g₂<1 为稳定区',boundary:'近轴、两凹面镜模型；g₁g₂=0 或 1 单列为临界。仅判断几何稳定性，不求模式或激光阈值。',challenge:'固定 R₁=−500 mm、R₂=−1000 mm，比较四个预设腔长。稳定性是否随腔长单调变化？'},
 fiber:{title:'光纤接收角与单模条件',subtitle:'把“能被导引”和“只支持一个空间模”分成两个问题。',source:'光电子学 · 第3章 §3.2',topic:'fiber',controls:[['delta','芯包折射率差 Δn（n₁=1.450）',.001,.04,.001,.006],['a','纤芯半径 a',2,10,.1,4.1,'μm'],['lambda','真空波长 λ₀',600,1650,1,1550,'nm'],['theta','空气中的入射角（相对光纤轴）',0,25,.1,5,'°']],formula:'NA=√(n₁²−n₂²)；V=2πa·NA/λ₀',boundary:'空气入射、理想弱导阶跃圆光纤；接收锥采用子午光线近似，不计算波动耦合效率。V<2.405 表示单空间模。',challenge:'先只改变入射角，再只改变波长。哪个改变接收判断，哪个改变支持的模式条件？'},
 detector:{title:'光电探测：从光子到电流',subtitle:'控制功率、波长与量子效率，追踪光电转换的每一步。',source:'光电子学 · 第7章 §7.3.1',topic:'detector',controls:[['lambda','真空波长 λ₀',400,1700,1,850,'nm'],['eta','外量子效率 η',0,1,.01,.8],['power','入射光功率 P',0,1000,1,100,'μW']],formula:'Φ=Pλ₀/(hc)；ℜ=ηeλ₀/(hc)；iₚ=ℜP',boundary:'理想、线性、无内部倍增；η 独立可调。不含真实吸收截止、暗电流、噪声、带宽与饱和。',challenge:'功率加倍时，光电流和响应度是否都加倍？将 η 调为零，再解释“光照存在但没有收集电流”。'}
 };
 const states={};let active='polar';
 const sel=document.querySelector('#lab-selector');sel.innerHTML=Object.entries(configs).map(([id,c],i)=>`<button data-experiment="${id}" class="experiment-tab ${i===0?'active':''}" aria-pressed="${i===0}"><span>0${i+1}</span>${c.title}</button>`).join('');
 const $l=s=>document.querySelector(s);
 const ctx=$l('#multi-optics').getContext('2d');
 function label(s,x,y,color='#b7cfd8',size=18,align='left'){ctx.fillStyle=color;ctx.font=`${size}px "Microsoft YaHei",sans-serif`;ctx.textAlign=align;ctx.fillText(s,x,y);}
 function line(x1,y1,x2,y2,color='#90dac6',width=2,dash=[]){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.setLineDash([]);}
 function dot(x,y,color='#ffca79',r=6){ctx.beginPath();ctx.fillStyle=color;ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
 function clear(){ctx.fillStyle='#102631';ctx.fillRect(0,0,1100,500);}
 function axes(box,xmin,xmax,ymin,ymax,xlabel,ylabel){const {x,y,w,h}=box;for(let i=0;i<=4;i++){const yy=y+h-i*h/4,xx=x+i*w/4;line(x,yy,x+w,yy,'#294653',1);line(xx,y,xx,y+h,'#203d49',1);const val=ymin+(ymax-ymin)*i/4;label(Math.abs(val)>=10?val.toFixed(0):val.toFixed(2),x-9,yy+5,'#8ca8b5',15,'right');label((xmin+(xmax-xmin)*i/4).toFixed(xmax-xmin<1?3:xmax<=5?1:0),xx,y+h+25,'#8ca8b5',15,'center')}label(xlabel,x+w/2,y+h+55,'#b7cfd8',17,'center');label(ylabel,x,y-20,'#b7cfd8',17);return {x:v=>x+(v-xmin)/(xmax-xmin)*w,y:v=>y+h-(v-ymin)/(ymax-ymin)*h,box};}
 function curve(ax,fn,xmin,xmax,color){ctx.save();ctx.beginPath();ctx.rect(ax.box.x,ax.box.y,ax.box.w,ax.box.h);ctx.clip();ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<=250;i++){const x=xmin+(xmax-xmin)*i/250,y=fn(x);if(i===0)ctx.moveTo(ax.x(x),ax.y(y));else ctx.lineTo(ax.x(x),ax.y(y))}ctx.stroke();ctx.restore();}
 function metrics(items){$l('#lab-metrics').innerHTML=items.map(([name,value])=>`<div><span>${name}</span><strong>${value}</strong></div>`).join('');}
 function draw(){const s=states[active],c=configs[active];if(!s)return;clear();let explanation='';
 if(active==='fresnel'){
  const r=Optics.fresnel(s.n1,s.n2,s.theta);metrics([['s 反射率 Rₛ',(r.rs*100).toFixed(2)+'%'],['p 反射率 Rₚ',(r.rp*100).toFixed(2)+'%'],['布儒斯特角',r.brewster.toFixed(2)+'°'],['临界角',r.critical===null?'不存在':r.critical.toFixed(2)+'°']]);
  ctx.fillStyle='#183d4d';ctx.fillRect(20,240,480,215);line(30,240,490,240,'#6d9eaf',3);line(265,80,265,421,'#688596',1,[7,7]);label(`n₁ = ${s.n1.toFixed(2)}`,45,70);label(`n₂ = ${s.n2.toFixed(2)}`,45,438);label('光路示意',265,35,'#b7cfd8',19,'center');const a=s.theta*Math.PI/180,len=160;line(265-len*Math.sin(a),240-len*Math.cos(a),265,240,'#ffcc81',4);line(265,240,265+len*Math.sin(a),240-len*Math.cos(a),'#91dec8',3);dot(265,240);label('入射',65,125,'#ffcc81',17);label('反射',380,125,'#91dec8',17);if(r.transmitted!==null){const b=r.transmitted*Math.PI/180;line(265,240,265+len*Math.sin(b),240+len*Math.cos(b),'#8bbcff',3);label('折射',380,405,'#8bbcff',17)}else{if(r.tir){for(let i=0;i<7;i++)line(275,250+i*11,470,250+i*11,`rgba(139,188,255,${.6*Math.exp(-i/2)})`,4)}else{line(265,240,485,240,'#8bbcff',4)}label(r.tir?'倏逝场：离界面越远越弱':'临界：折射方向沿界面',260,385,'#8bbcff',16,'center')}
  const ax=axes({x:595,y:85,w:455,h:310},0,90,0,1,'入射角 θ₁ / °','功率反射率 R');curve(ax,x=>Optics.fresnel(s.n1,s.n2,x).rs,0,89.99,'#91dec8');curve(ax,x=>Optics.fresnel(s.n1,s.n2,x).rp,0,89.99,'#8bbcff');dot(ax.x(s.theta),ax.y(r.rs),'#91dec8');dot(ax.x(s.theta),ax.y(r.rp),'#8bbcff');label('s 偏振',720,38,'#91dec8');label('p 偏振',860,38,'#8bbcff');explanation=Math.abs(s.n1-s.n2)<1e-10?'两侧折射率相同：本模型中各角度的 s、p 反射率都为零，不存在一个特殊的零反射角。':r.tir?'进入全反射区，Rₛ=Rₚ=1；第二介质中仍有倏逝场，图中衰减条纹只示意其存在，不表示定量衰减长度。':r.transmitted===null?'到达临界角，折射传播方向沿界面。继续增大入射角才进入全反射区。':`折射角为 ${r.transmitted.toFixed(2)}°。${Math.abs(s.theta-r.brewster)<.1?'接近布儒斯特角，p 反射率接近零；s 分量仍可反射。':'沿曲线比较两种偏振，注意 θ 都相对法线测量。'}`;
 }else if(active==='gaussian'){
  const r=Optics.gaussian(s.w0,s.lambda,s.z),maxW=Optics.gaussian(s.w0,s.lambda,500).w;metrics([['瑞利距离 z₀',r.zr.toFixed(2)+' mm'],['当前半径 W(z)',(r.w*1000).toFixed(1)+' μm'],['远场半角 θ₀',r.divergence.toFixed(3)+' mrad'],['当前轴上光强 / 束腰峰值',(100*r.relativePeak).toFixed(2)+'%']]);
  const ax=axes({x:80,y:85,w:460,h:310},0,500,0,maxW*1.15,'离束腰距离 z / mm','1/e² 光强半径 W / mm');curve(ax,x=>Optics.gaussian(s.w0,s.lambda,x).w,0,500,'#91dec8');line(ax.x(s.z),85,ax.x(s.z),395,'#ffcc81',1,[6,6]);dot(ax.x(s.z),ax.y(r.w));const span=Math.max(r.w*2,.05);const bx=axes({x:665,y:85,w:365,h:310},-span,span,0,1,'横向位置 r / mm','当前截面 I(r) / I(0)');curve(bx,x=>Math.exp(-2*x*x/(r.w*r.w)),-span,span,'#8bbcff');label('传播半径',260,35,'#91dec8',19,'center');label('横截面光强',850,35,'#8bbcff',19,'center');explanation=`当前位置 z/z₀ = ${(s.z/r.zr).toFixed(2)}。右图以当前截面轴上强度归一化，峰值恒为 1；绝对峰值变化请看上面的百分比。横轴随光斑范围自动缩放，请结合刻度比较宽度。`;
 }else if(active==='cavity'){
  const r=Optics.cavity(s.d,-s.r1,-s.r2);metrics([['g₁',r.g1.toFixed(3)],['g₂',r.g2.toFixed(3)],['g₁g₂',r.p.toFixed(4)],['稳定性',r.state]]);const low=Math.min(-2,Math.floor(Math.min(r.g1,r.g2)-.3));const ax=axes({x:85,y:85,w:420,h:310},low,1.2,low,1.2,'g₁','g₂');for(let i=0;i<105;i++)for(let j=0;j<78;j++){const gx=low+(1.2-low)*i/105,gy=low+(1.2-low)*j/78,p=gx*gy;if(p>0&&p<1){ctx.fillStyle='#25726266';ctx.fillRect(ax.x(gx),ax.y(gy)-(310/78),5,5)}}line(ax.x(0),85,ax.x(0),395,'#7895a3',1);line(85,ax.y(0),505,ax.y(0),'#7895a3',1);dot(ax.x(r.g1),ax.y(r.g2));label('绿色为稳定区；黄色点为当前腔',65,38,'#91dec8',18);const ylo=Math.min(-.5,Math.floor(r.p)-.2),yhi=Math.max(2,Math.ceil(r.p)+.2);const bx=axes({x:650,y:85,w:385,h:310},0,2000,ylo,yhi,'腔长 d / mm','g₁g₂（超出纵轴部分裁切）');ctx.fillStyle='#25726255';ctx.fillRect(650,bx.y(1),385,bx.y(0)-bx.y(1));curve(bx,d=>Optics.cavity(d,-s.r1,-s.r2).p,0,2000,'#8bbcff');dot(bx.x(s.d),bx.y(r.p));label('固定曲率，改变腔长',820,38,'#8bbcff',18,'center');explanation=`R₁=−${s.r1} mm、R₂=−${s.r2} mm。当前判定为“${r.state}”。教材 g=1+d/R 中的加号来自凹镜 R<0 的符号约定。稳定图只讨论几何传播；不据此判断激光一定振荡。`;
 }else if(active==='fiber'){
  const r=Optics.fiber(s.delta,s.a,s.lambda,s.theta);metrics([['数值孔径 NA',r.na.toFixed(4)],['接收半角 θa',r.acceptance.toFixed(2)+'°'],['V 参数',r.v.toFixed(3)],['空间模条件',r.atCutoff?'位于截止边界':r.single?'单空间模':'超过单模截止']]);
  label('端面接收示意（非比例图）',270,38,'#91dec8',18,'center');ctx.fillStyle='#244453';ctx.fillRect(235,150,290,180);ctx.fillStyle='#327466';ctx.fillRect(235,195,290,90);line(40,240,535,240,'#88a1ae',1,[6,6]);const rayY=240-190*Math.tan(s.theta*Math.PI/180),coneY=190*Math.tan(r.acceptance*Math.PI/180);ctx.fillStyle='#81d1bb22';ctx.beginPath();ctx.moveTo(235,240);ctx.lineTo(45,240-coneY);ctx.lineTo(45,240+coneY);ctx.closePath();ctx.fill();line(45,rayY,235,240,'#ffcc81',4);const inner=Math.asin(Math.sin(s.theta*Math.PI/180)/r.n1);line(235,240,515,240+280*Math.tan(inner),r.accepted?'#91dec8':'#f1a17b',4);label('纤芯 n₁=1.450',300,225,'#d4ede3',16);label(`包层 n₂=${r.n2.toFixed(3)}`,300,310,'#c6dbe3',16);label(`入射 ${s.theta.toFixed(1)}° ${r.accepted?'≤':'>'} 接收半角`,280,385,r.accepted?'#91dec8':'#ffb083',18,'center');const maxV=Optics.fiber(s.delta,s.a,600,0).v*1.15;const ax=axes({x:640,y:85,w:400,h:310},600,1650,0,maxV,'真空波长 λ₀ / nm','V 参数');curve(ax,l=>Optics.fiber(s.delta,s.a,l,0).v,600,1650,'#8bbcff');line(640,ax.y(2.405),1040,ax.y(2.405),'#ffcc81',2,[7,6]);label('截止 V=2.405',650,ax.y(2.405)-10,'#ffcc81',16);dot(ax.x(s.lambda),ax.y(r.v));explanation=`${r.accepted?'满足子午光线的接收条件':'超出子午光线接收锥，不能以此角度形成该近似下的长距离导引'}。给定 a 与 NA 时，截止真空波长约 ${r.cutoff.toFixed(0)} nm，较长波长使 V 降低。此判断不等于实际耦合效率。`;
 }else if(active==='detector'){
  const r=Optics.detector(s.lambda,s.eta,s.power);metrics([['光子能量',(r.energy/1.602176634e-19).toFixed(3)+' eV'],['光子通量 Φ',r.flux.toExponential(2)+' s⁻¹'],['响应度 ℜ',r.responsivity.toFixed(4)+' A/W'],['光生电流 iₚ',r.current.toFixed(2)+' μA']]);
  const boxes=[['入射光',`${s.power} μW`,'#ffcc81'],['有效收集',`η = ${(s.eta*100).toFixed(0)}%`,'#91dec8'],['光生电流',`${r.current.toFixed(2)} μA`,'#8bbcff']];boxes.forEach(([a,b,col],i)=>{const y=70+i*125;ctx.fillStyle='#1b3b49';ctx.fillRect(80,y,405,88);label(a,108,y+32,col,19);label(b,457,y+58,col,25,'right');if(i<2){line(282,y+92,282,y+120,'#63818f',3);label('↓',300,y+119,'#63818f',22)}});const ax=axes({x:640,y:85,w:400,h:310},0,1000,0,1500,'入射光功率 / μW','光生电流 / μA');curve(ax,p=>Optics.detector(s.lambda,s.eta,p).current,0,1000,'#8bbcff');dot(ax.x(s.power),ax.y(r.current));explanation=`这条直线的斜率为 ${r.responsivity.toFixed(4)} A/W。在波长与 η 不变时，改变功率只沿直线移动，不改变响应度。这里的 η 不含波长截止模型，因此不能用此曲线替代真实器件的响应谱。`;
 }
 $l('#multi-explain').textContent=explanation;
 }
 function controls(){const c=configs[active],s=states[active];$l('#multi-controls').innerHTML=c.controls.map(([id,title,min,max,step,,unit=''])=>`<div class="parameter"><label for="param-${id}">${title}<output id="value-${id}">${Number(s[id].toFixed(3))} ${unit}</output></label><input id="param-${id}" data-param="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${s[id]}"><div class="range-label"><span>${min} ${unit}</span><span>${max} ${unit}</span></div></div>`).join('');$l('#multi-controls').querySelectorAll('input').forEach(el=>el.oninput=()=>{s[el.dataset.param]=Number(el.value);const conf=c.controls.find(a=>a[0]===el.dataset.param);$l('#value-'+el.dataset.param).textContent=el.value+' '+(conf[6]||'');draw()});}
 function set(p){Object.assign(states[active],p);controls();draw()}
 function presets(){const actions={fresnel:[['空气 → 玻璃',()=>set({n1:1,n2:1.5,theta:56.31})],['玻璃 → 空气',()=>set({n1:1.5,n2:1,theta:50})],['布儒斯特角',()=>set({theta:Optics.fresnel(states[active].n1,states[active].n2,0).brewster})],['临界角',()=>{const a=Optics.fresnel(states[active].n1,states[active].n2,0).critical;if(a!==null)set({theta:a});else $l('#multi-explain').textContent='当前 n₁≤n₂，不存在全反射临界角。请先切换玻璃→空气。'}]],gaussian:[['束腰位置',()=>set({z:0})],['一个瑞利距离',()=>{const s=states[active],z=Optics.gaussian(s.w0,s.lambda,0).zr;if(z<=500)set({z});else $l('#multi-explain').textContent=`当前瑞利距离 ${z.toFixed(2)} mm 超出 500 mm 演示范围；减小束腰或增大波长后重试。`}]],cavity:[250,750,1250,1500].map(d=>[d+' mm',()=>set({d,r1:500,r2:1000})]),fiber:[['1550 nm',()=>set({lambda:1550})],['850 nm',()=>set({lambda:850})]],detector:[['100 μW',()=>set({power:100})],['200 μW',()=>set({power:200})],['遮光 P=0',()=>set({power:0})]]}[active]||[];$l('#multi-presets').innerHTML='';for(const [name,fn]of actions){const b=document.createElement('button');b.textContent=name;b.onclick=fn;$l('#multi-presets').append(b)}}
 function select(id){if(!configs[id])return;active=id;const c=configs[id];if(rotation){clearInterval(rotation);rotation=null;document.querySelector('#animate').textContent='▷ 自动旋转'}document.querySelectorAll('[data-experiment]').forEach(b=>{b.classList.toggle('active',b.dataset.experiment===id);b.setAttribute('aria-pressed',b.dataset.experiment===id?'true':'false')});$l('#polar-workbench').hidden=id!=='polar';$l('#expanded-workbench').hidden=id==='polar';$l('#lab .page-heading h1').textContent=c.title;$l('#lab .page-heading p').textContent=c.subtitle;$l('#lab .page-heading .tag').textContent=c.source;$l('#experiment-source').textContent=c.source;$l('#experiment-lesson').onclick=()=>{document.querySelector('#lesson-topic').value=c.topic;generatePlan();showView('teacher')};if(id==='polar'){drawLab();return}if(!states[id])states[id]=Object.fromEntries(c.controls.map(a=>[a[0],a[5]]));$l('#multi-formula').textContent=c.formula;$l('#multi-boundary').textContent=c.boundary;$l('#multi-challenge').textContent=c.challenge;controls();presets();draw();}
 sel.addEventListener('click',e=>{const b=e.target.closest('[data-experiment]');if(b)select(b.dataset.experiment)});$l('#reset-experiment').onclick=()=>{delete states[active];select(active)};
 window.openExperiment=id=>{showView('lab');select(id)};select('polar');
})();
