/* Source text is escaped before rendering; TeX never receives trusted HTML access. */
(function(scope){'use strict';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function typeset(tex,display=false){let source=tex.trim();try{return scope.katex.renderToString(source,{displayMode:display,throwOnError:true,trust:false,strict:'ignore',maxExpand:1000,maxSize:20,output:'htmlAndMathml'});}catch(error){return `<span class="math-fallback" title="此式的原稿语法需要校对">${escape(source)}<small>原稿公式待校对</small></span>`}}
function render(raw,options={}){const tokens=[];const store=html=>'\uE000'+(tokens.push(html)-1)+'\uE001';let source=String(raw||'').replace(/<!--[^]*?-->/g,'');source=source.replace(/\$\$([\s\S]*?)\$\$|\$([^$\n]+)\$/g,(_,block,inline)=>store(typeset(block===undefined?inline:block,block!==undefined)));source=source.replace(/!\[([^\]]*)\]\(([^)]+)\)/g,(_,alt,url)=>{const image=typeof BOOK_FIGURES!=='undefined'?BOOK_FIGURES[url]:null;const available=image||(typeof BOOK_FIGURE_CHUNKS!=='undefined'&&BOOK_FIGURE_CHUNKS[url]!==undefined);return store(available?`<figure class="book-figure"><img loading="lazy" ${image?`src="${image}"`:`data-book-image="${escape(url)}"`} alt="${escape(alt||'教材原图')}"/><figcaption>${escape(alt||'教材原图 · 与原文保留相同位置')}</figcaption></figure>`:'<p class="source-figure-note">此图见教材原页。</p>')});
const html=source.split(/\n\s*\n/).map(block=>{if(/^#{1,6}\s/.test(block)){const title=block.replace(/^#{1,6}\s*/,'');return '<h3>'+escape(title)+'</h3>'}return '<p>'+escape(block).replace(/\n/g,'<br>')+'</p>'}).join('\n').replace(/\uE000(\d+)\uE001/g,(_,n)=>tokens[+n]);return html;}
const imageLoads=new Map();
function hydrate(root){const images=[...root.querySelectorAll('img[data-book-image]')];for(const img of images){const key=img.dataset.bookImage;if(typeof BOOK_FIGURE_CHUNKS==='undefined'||BOOK_FIGURE_CHUNKS[key]===undefined)continue;const ch=BOOK_FIGURE_CHUNKS[key];if(!imageLoads.has(ch)){imageLoads.set(ch,new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='book-images/'+ch+'.js';script.onload=resolve;script.onerror=reject;document.head.append(script)}))}imageLoads.get(ch).then(()=>{if(img.isConnected&&BOOK_FIGURES[key]){img.src=BOOK_FIGURES[key];img.removeAttribute('data-book-image')}}).catch(()=>{img.alt='教材原图未能加载，可重新打开本节重试。';imageLoads.delete(ch)});}}
scope.CourseMath={render,typeset,escape,hydrate};if(typeof module!=='undefined')module.exports=scope.CourseMath;
})(typeof window==='undefined'?globalThis:window);
