(function(){'use strict';
const host=document.querySelector('#reader-view'),esc=CourseMath.escape;
let data=null,loading=null,active=false,unit=null,page=28,mode='parallel',query='',focusId=null,pdfUrl=null,renderToken=0;
let helperCollapsed=read('photon-helper-collapsed',true)!==false;
const imageLoads=new Map();let vocabulary=read('photon-vocabulary',[]),pending=read('photon-pending',[]),notes=read('photon-reader-notes',{});
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
function status(s){const el=host.querySelector('#reader-status');if(el)el.textContent=s}
function load(){if(data)return Promise.resolve();if(!loading)loading=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='photonics-data.js?v=6';s.onload=()=>{data=window.PHOTONICS_DATA;resolve()};s.onerror=()=>{s.remove();loading=null;reject(Error('英文资料未加载。请检查网络或解压后的文件是否完整。'))};document.head.append(s)});return loading}
async function start(parts=[]){active=true;host.innerHTML='<div class="reader-loading">正在打开英文教材…</div>';try{await load();if(!active)return;const last=read('photon-reading-place',{}),id=parts[1]||last.unit||'1.1';unit=data.units.find(u=>u.id===id)||data.units[0];page=Number(parts[2])||(parts[1]?unit.start:(last.page||unit.start));page=Math.max(1,Math.min(1208,Math.floor(page)));mode=read('photon-reader-mode','parallel');if(!['parallel','chinese','english'].includes(mode))mode='parallel';focusId=parts[3]||null;render()}catch(e){host.innerHTML=`<div class="reader-loading"><p>${esc(e.message)}</p><button data-reader-retry>重新加载</button></div>`}}
function stop(){active=false;renderToken++}
function navigate(id,p,block=''){location.hash=`reader/${id}/${p}${block?'/'+block:''}`}
function sourceLabel(b){return `PDF ${b.page} / 书内 ${b.page>26?b.page-26:'前置页'} · ${b.id}`}
function excerpt(text,n=170){return String(text).replace(/\$\$[\s\S]*?\$\$|\$[^$]*\$/g,'〔数学表达见原文〕').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').slice(0,n)}
function pageSection(){return data.sections.find(s=>page>=s.pdf_start&&page<=s.pdf_end)}
function termText(text){const terms=[...data.terms].sort((a,b)=>b.en.length-a.en.length),rx=new RegExp('\\b('+terms.map(t=>t.en.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')+')\\b','gi');let out='',from=0;for(const m of text.matchAll(rx)){const term=terms.find(t=>t.en.toLowerCase()===m[0].toLowerCase());out+=esc(text.slice(from,m.index))+`<button class="reader-term" data-term="${term.id}" title="${esc(term.zh)}">${esc(m[0])}</button>`;from=m.index+m[0].length}return out+esc(text.slice(from))}
function prose(text,english=false){return String(text||'').split(/(\$\$[\s\S]*?\$\$|\$[^$\n]+\$)/g).map(s=>{if(s.startsWith('$')){const d=s.startsWith('$$'),tex=s.slice(d?2:1,d?-2:-1);try{return katex.renderToString(tex,{throwOnError:true,trust:false,strict:'ignore',displayMode:d,maxExpand:500,maxSize:20})}catch{return '<span class="reader-math-warning" title="此处 OCR 数学表达需回原页核对">〔原式待核对〕</span>'}}return (english?termText(s):esc(s)).replace(/\n/g,'<br>')}).join('')}
function blockHtml(b){const where=`<div class="reader-block-source"><span>${sourceLabel(b)}${b.corrected?' · OCR 已据原页修正':''}</span><button data-focus="${b.id}">词句与笔记</button></div>`;
 if(b.type==='equation')return `<section class="reader-equation" id="read-${b.id}">${where}<button class="reader-zoom" data-zoom="${b.id}" aria-label="放大公式 ${b.id}"><img data-en-image="${b.id}" alt="${b.id} 公式原图，PDF 第 ${b.page} 页"></button><small>原书公式 · 点击放大</small></section>`;
 if(b.type==='code')return `<section class="reader-block" id="read-${b.id}">${where}<p class="reader-pending">此段被 OCR 识别为复杂结构，排版尚待核对。请关联本机 PDF 查看原页。</p><button data-reader-pdf>核对 PDF 第 ${b.page} 页</button><details class="reader-raw-ocr"><summary>查看原始 OCR 提取（未经排版校对）</summary><pre>${esc(b.en)}</pre></details></section>`;
 if(b.type==='table')return `<section class="reader-block" id="read-${b.id}">${where}<button class="reader-zoom" data-zoom="${b.id}" aria-label="放大表格 ${b.id}"><img loading="lazy" data-en-image="${b.id}" alt="${b.id} 表格原图"></button><p class="reader-pending">表格文字与公式保留在原图中，点击可放大核对。${b.zh?prose(b.zh):'本表中文尚待补充。'}</p><button class="reader-queue" data-queue="${b.id}">${pending.includes(b.id)?'已加入待译清单':'加入待译清单'}</button></section>`;
 if(!b.en.trim()&&!b.image)return '';
 const image=b.image?`<button class="reader-zoom" data-zoom="${b.id}" aria-label="放大原图 ${b.id}"><img loading="lazy" data-en-image="${b.id}" alt="${b.id} 教材原图，PDF 第 ${b.page} 页"></button>`:'';
 const zh=b.zh?prose(b.zh):`<p class="reader-pending">本段尚未翻译，保留英文原文供核对。</p><button class="reader-queue" data-queue="${b.id}">${pending.includes(b.id)?'已加入待译清单':'加入待译清单'}</button>`;
 return `<section id="read-${b.id}" class="reader-block ${b.level?'reader-heading-block':''} ${!b.zh?'untranslated':''}">${where}${image}${b.en.trim()?`<div class="reader-pair"><div class="en-prose" lang="en" data-block="${b.id}"><small>英文原文</small><div>${prose(b.en,true)}</div></div><div class="zh-prose" lang="zh-CN"><small>${b.zh?'中文译文':'中文待译'}</small><div>${zh}</div></div></div>`:''}${b.note?`<button class="reader-insight-link" data-focus="${b.id}">辨析这段的条件、语气与易误读处</button>`:''}</section>`}
function render(){const token=++renderToken,sec=pageSection(),blocks=data.blocks.filter(b=>b.page===page),outside=page<unit.start||page>unit.end;
 host.innerHTML=`<div class="reader-banner"><div><p>中文课程引路 · 英文教材精读</p><h1>把英文读懂，<br>把原理读透。</h1></div><div class="reader-book-title"><b>Fundamentals<br>of Photonics</b><span>Saleh & Teich / Second Edition</span><small>全书 1,208 页原文 · ${data.translated} 块中文对照，持续补译</small></div></div>
 <div class="reader-layout ${helperCollapsed?'helper-collapsed':''}"><aside class="reader-outline"><div class="reader-outline-title"><b>按中文教材顺序</b><button data-show-vocab>词句本 ${vocabulary.length}</button></div><label for="reader-outline-query" class="sr-only">搜索中文课节</label><input id="reader-outline-query" type="search" placeholder="找课程知识点，如：高斯光束" value="${esc(query)}"><div id="reader-outline-items"></div><details class="reader-english-index"><summary>也可以按英文全书浏览</summary><label for="english-chapter">英文书目录</label><select id="english-chapter">${data.sections.map(s=>`<option value="${s.pdf_start}" ${sec.slug===s.slug?'selected':''}>${esc(s.title_en)} / ${esc(s.title_zh)}</option>`).join('')}</select><p>章节顺序以英文原书为准。</p></details></aside>
 <div class="reader-center"><div class="reader-match"><span>${esc(unit.id+' '+unit.title)}</span><h2>${esc(unit.label)}</h2><p>${unit.relation==='未对应'?'未找到直接对应，仅提供背景阅读':unit.inherited?'同主题参考范围（沿用上级小节）':unit.relation==='补充'?'补充阅读；两书范围不完全相同':'主题对应；页内可能包含相邻小节'} · 英文书 ${unit.start-26}–${unit.end-26} 页 / PDF ${unit.start}–${unit.end}</p><div class="reader-match-actions"><span>此范围 ${unit.translated}/${unit.total} 个文字块已有译文</span><a href="#course/${unit.id}/book">对照中文教材</a><a href="#course/${unit.id}/experiment">本节原理演示</a></div></div>
 <div class="reader-tools"><div class="reader-modes" aria-label="阅读模式">${[['parallel','双语对照'],['chinese','中文优先'],['english','英文先读']].map(([m,t])=>`<button data-reader-mode="${m}" aria-pressed="${mode===m}" class="${mode===m?'active':''}">${t}</button>`).join('')}</div><button data-reader-search>检索英文全书</button><button data-show-pending>待译清单 ${pending.length}</button><button data-reader-progress>全书翻译进度</button><button data-toggle-helper aria-controls="reader-helper-panel" aria-expanded="${!helperCollapsed}">${helperCollapsed?'展开笔记栏':'收起笔记栏'}</button></div>
 <div class="reader-pagebar"><button data-reader-page="${page-1}" ${page<=1?'disabled':''}>上一页</button><form id="reader-jump"><label for="reader-page-number">PDF 页</label><input id="reader-page-number" type="number" min="1" max="1208" value="${page}"><button>跳转</button></form><span>书内 ${page>26?page-26:'前置'} 页</span><button data-reader-page="${page+1}" ${page>=1208?'disabled':''}>下一页</button></div>
 ${outside?`<div class="reader-outside">当前页在本节对应范围之外。<button data-reader-page="${unit.start}">返回对应起始页</button></div>`:''}
 <div class="reader-source-notice">${esc(sec.title_en)} · 原文来自扫描 OCR，显示公式采用原图。<button data-reader-pdf>关联本机 PDF 核对原页</button>${data.progress.verifiedRanges.some(([a,z])=>page>=a&&page<=z)?'<span>本页译文已对照原页核读</span>':''}</div>
 <article id="bilingual-paper" class="bilingual-paper mode-${mode}">${blocks.map(blockHtml).join('')||'<p>此页没有可提取的正文，请查看原 PDF。</p>'}</article><div class="reader-page-bottom"><button data-reader-page="${page+1}" ${page>=1208?'disabled':''}>继续阅读下一页</button><button data-next-unit>按中文目录进入下一节</button></div><p id="reader-status" role="status"></p></div>
 <aside class="reader-helper" id="reader-helper-panel" ${helperCollapsed?'hidden':''}><div class="reader-helper-sticky"><div class="reader-helper-top"><b>词句与笔记</b><button data-toggle-helper aria-controls="reader-helper-panel" aria-expanded="true">收起</button></div><div id="reader-context"><span class="reader-helper-label">读懂这一句</span><h3>点词看语境，选句记疑问。</h3><p>点击英文中带下划线的词语，查看光学语境中的含义。也可以选中一段英文，保存自己的释义与疑问。</p><div class="reader-helper-example"><b>mode → 模式</b><p>同一个词在光学中可能有严格定义。阅读时同时核对适用条件和符号约定。</p></div><p class="reader-helper-note">释义与辨析为辅助讲解；逐段译文保持在正文右侧。未接入实时机器翻译。</p></div></div></aside></div>
 <dialog id="reader-dialog" class="reader-dialog"><button class="reader-dialog-close" data-close-reader aria-label="关闭阅读工具">×</button><div id="reader-dialog-body"></div></dialog><input type="file" id="reader-pdf-file" accept="application/pdf,.pdf" hidden>`;
 renderOutline();host.querySelector('#reader-outline-query').oninput=e=>{query=e.target.value;renderOutline()};host.querySelector('#english-chapter').onchange=e=>navigate(unit.id,+e.target.value);host.querySelector('#reader-jump').onsubmit=e=>{e.preventDefault();const n=+host.querySelector('#reader-page-number').value;if(Number.isInteger(n)&&n>=1&&n<=1208)navigate(unit.id,n)};
 host.querySelector('#reader-pdf-file').onchange=e=>{const file=e.target.files[0];if(!file)return;if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl=URL.createObjectURL(file);openPdf()};
 save('photon-reading-place',{unit:unit.id,page});hydrateImages(token);if(focusId){const b=data.blocks.find(x=>x.id===focusId&&x.page===page);if(b){showContext(b,null,'',false);host.querySelector('#read-'+b.id)?.scrollIntoView({block:'center',behavior:'instant'})}}
}
function renderOutline(){const tree=host.querySelector('#reader-outline-items'),s=query.toLowerCase();tree.innerHTML=data.chapters.map(c=>{const list=data.units.filter(u=>u.chapter===c.id&&(!s||(u.id+' '+u.title+' '+u.label).toLowerCase().includes(s)));return list.length?`<details ${c.id===unit.chapter||s?'open':''}><summary>第 ${c.id} 章 ${esc(c.title)}</summary>${list.map(u=>`<button data-reader-unit="${u.id}" class="${u.id===unit.id?'active':''}"><span>${u.id} ${esc(u.title)}</span><small>${u.translated?'有译文':u.relation==='未对应'?'背景阅读':'原文待译'}</small></button>`).join('')}</details>`:''}).join('')||'<p>没有匹配的课节。</p>'}
async function hydrateImages(token){const ids=[...host.querySelectorAll('[data-en-image]')].map(e=>e.dataset.enImage),chunks=[...new Set(ids.map(id=>data.imageManifest[id]))];for(const ch of chunks){if(!imageLoads.has(ch))imageLoads.set(ch,new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='photonics/'+ch+'-images.js';s.onload=resolve;s.onerror=()=>{s.remove();imageLoads.delete(ch);reject(Error('原图加载失败'))};document.head.append(s)}));try{await imageLoads.get(ch);if(token!==renderToken||!active)return;for(const img of host.querySelectorAll('[data-en-image]'))if(window.PHOTONICS_IMAGES[img.dataset.enImage])img.src=window.PHOTONICS_IMAGES[img.dataset.enImage]}catch{if(token===renderToken)status('原图未能加载，请点“重新加载原图”重试。');if(token===renderToken)host.querySelector('#reader-status').insertAdjacentHTML('beforeend',' <button data-retry-images>重新加载原图</button>')}}}
function setHelperCollapsed(collapsed,restoreFocus=false){helperCollapsed=collapsed;save('photon-helper-collapsed',collapsed);host.querySelector('.reader-layout').classList.toggle('helper-collapsed',collapsed);host.querySelector('#reader-helper-panel').hidden=collapsed;host.querySelectorAll('[data-toggle-helper]').forEach(btn=>{btn.setAttribute('aria-expanded',String(!collapsed));if(btn.closest('.reader-tools'))btn.textContent=collapsed?'展开笔记栏':'收起笔记栏'});if(collapsed&&restoreFocus)host.querySelector('.reader-tools [data-toggle-helper]').focus({preventScroll:true})}
function showContext(b,term=null,selection='',reveal=true){if(reveal)setHelperCollapsed(false);focusId=b.id;const note=b.note,chosen=selection||term?.en||note?.phrase||'',known=term||data.terms.find(t=>t.en.toLowerCase()===chosen.toLowerCase()),saved=notes[b.id]||'';
 host.querySelector('#reader-context').innerHTML=`<span class="reader-helper-label">${sourceLabel(b)}</span><h3>${esc(chosen||'这一段的阅读笔记')}</h3>${known?`<div class="reader-meaning"><b>${esc(known.zh)}</b><p>${esc(known.meaning)}</p><button id="reader-save-term">加入词句本</button></div>`:selection?'<p>词典尚未收录这段文字，可在下方记录自己的理解；当前不会自动生成译文。</p>':''}${note?`<div class="reader-language-note"><b>表达与逻辑</b><p><i lang="en">${esc(note.phrase)}</i><br>${esc(note.meaning)}</p><b>辅助辨析</b><p>${esc(note.logic)}</p><b>试着回答</b><p>${esc(note.question)}</p></div>`:''}<label for="reader-personal-note">我的释义 / 疑问</label><textarea id="reader-personal-note" placeholder="写下你的理解或需要核对的地方">${esc(saved)}</textarea><button id="reader-save-note">保存本段笔记${chosen?'与所选词句':''}</button><p id="reader-note-status" role="status"></p><small class="reader-helper-note">以上提示是辅助讲解，不属于教材原文。笔记仅保存于此浏览器。</small>`;
 const keep=()=>{notes[b.id]=host.querySelector('#reader-personal-note').value;const ok=save('photon-reader-notes',notes);if(chosen)addVocab(b,chosen,known?.zh||'',known?.meaning||notes[b.id]);host.querySelector('#reader-note-status').textContent=ok?'已保存在此浏览器':'未能保存，请复制笔记备用'};host.querySelector('#reader-save-note').onclick=keep;
 if(known)host.querySelector('#reader-save-term').onclick=()=>{addVocab(b,known.en,known.zh,known.meaning);host.querySelector('#reader-note-status').textContent='已加入词句本'};
 if(reveal&&matchMedia('(max-width: 1100px)').matches)host.querySelector('#reader-context').scrollIntoView({block:'nearest',behavior:'smooth'});
}
function addVocab(b,en,zh,meaning){if(!vocabulary.some(v=>v.en===en&&v.block===b.id))vocabulary.push({en,zh,meaning,block:b.id,page:b.page,unit:unit.id,at:new Date().toISOString()});if(!save('photon-vocabulary',vocabulary))status('浏览器不允许保存，请先导出词句本。');const btn=host.querySelector('[data-show-vocab]');if(btn)btn.textContent='词句本 '+vocabulary.length}
function dialog(content){host.querySelector('#reader-dialog-body').innerHTML=content;host.querySelector('#reader-dialog').showModal()}
function close(){host.querySelector('#reader-dialog').close()}
function download(name,text,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function listSaved(kind){const isV=kind==='vocab',list=isV?vocabulary:pending.map(id=>data.blocks.find(b=>b.id===id)).filter(Boolean);dialog(`<h2>${isV?'我的词句本':'待译清单'}</h2><p>${isV?'词句保留原段落位置，可返回语境复习。':'清单仅记录翻译需求，不会在后台自动翻译。可导出后继续补译。'}</p><button data-export-reader="${kind}">导出${isV?'词句本':'待译原文'}</button><div class="reader-saved-list">${list.map((x,i)=>`<article><b>${esc(isV?x.en:x.id+' · PDF '+x.page)}</b><p>${esc(isV?(x.zh+' '+x.meaning):excerpt(x.en,220))}</p><button data-return-block="${isV?x.block:x.id}" data-return-unit="${isV?x.unit:unit.id}">回到原文</button><button data-remove-reader="${kind}" data-remove-index="${i}">移出清单</button></article>`).join('')||'<p>还没有记录。阅读时选词保存，或把尚未翻译的段落加入清单。</p>'}</div>`)}
function progressDialog(){const p=data.progress,labels={translated:'已译',partial:'部分已译',pending:'待译','no-text':'无文字'};dialog(`<h2>全书逐段翻译进度</h2><p>已译 <strong>${p.translated}</strong> / ${p.total} 个文字块，剩余 ${p.remaining} 个。公式和无文字原图保留原貌，不计入文字翻译数量。</p><p>${esc(p.policy)} 已译页段仍保留原文与出处，图内标签以原图为准。以下是补译计划与已完成记录，网页不会自行在后台翻译。</p><a href="english-translation-progress.md" target="_blank" rel="noopener">查看完整页段记录</a><div class="reader-progress-list">${p.batches.map(b=>`<article><div><b>PDF ${b.start}–${b.end} · ${esc(b.title)}</b><span>${labels[b.status]} · ${b.translated}/${b.total} 块</span><progress value="${b.translated}" max="${b.total||1}" aria-label="PDF ${b.start} 到 ${b.end} 页已译 ${b.translated} 共 ${b.total} 块"></progress></div><button data-reader-batch="${b.id}">${b.remaining?'查看待译位置':'阅读本段'}</button></article>`).join('')}</div>`)}
function searchDialog(){dialog('<h2>检索英文原书与已有译文</h2><form id="reader-full-search"><label class="sr-only" for="reader-search-input">检索词</label><input id="reader-search-input" placeholder="English 或中文，例如 ray-transfer / 光线传递"><button>检索</button></form><p id="reader-search-count" role="status"></p><div id="reader-search-results"></div>');host.querySelector('#reader-full-search').onsubmit=e=>{e.preventDefault();const text=host.querySelector('#reader-search-input').value.trim().toLowerCase(),words=text.split(/\s+/).filter(Boolean);const hits=words.length?data.blocks.filter(b=>words.every(w=>(b.en+' '+b.zh).toLowerCase().includes(w))):[];host.querySelector('#reader-search-count').textContent=`找到 ${hits.length} 个段落，显示前 40 条。中文只检索已有译文。`;host.querySelector('#reader-search-results').innerHTML=hits.slice(0,40).map(b=>`<button class="reader-hit" data-return-block="${b.id}" data-return-unit="${unit.id}"><b>${sourceLabel(b)}</b><span>${esc(excerpt(b.zh||b.en))}</span></button>`).join('')}}
function openPdf(){if(!pdfUrl){host.querySelector('#reader-pdf-file').click();return}dialog(`<h2>原 PDF 第 ${page} 页</h2><p>此文件由你从本机选择，只在当前浏览器会话读取。</p><a href="${pdfUrl}#page=${page}" target="_blank" rel="noopener">在新窗口查看原页</a><button data-replace-pdf>重新选择 PDF</button><object type="application/pdf" data="${pdfUrl}#page=${page}" class="reader-original-pdf"><p>浏览器未能内嵌 PDF，请使用上方链接。</p></object>`)}
host.addEventListener('click',e=>{const el=e.target.closest('button,[data-reader-unit]');if(!el)return;
 if(el.hasAttribute('data-reader-retry')){start(location.hash.slice(1).split('/'));return}
 if(!data)return;
 if(el.hasAttribute('data-toggle-helper'))setHelperCollapsed(!helperCollapsed,true);
 else if(el.hasAttribute('data-reader-progress'))progressDialog();
 else if(el.dataset.readerBatch){const b=data.progress.batches.find(b=>b.id===el.dataset.readerBatch);if(b){close();navigate(b.unit,b.nextPage)}}
 else if(el.dataset.readerUnit){const u=data.units.find(u=>u.id===el.dataset.readerUnit);navigate(u.id,u.start)}
 else if(el.dataset.readerPage)navigate(unit.id,+el.dataset.readerPage);
 else if(el.dataset.readerMode){mode=el.dataset.readerMode;save('photon-reader-mode',mode);host.querySelector('#bilingual-paper').className='bilingual-paper mode-'+mode;host.querySelectorAll('[data-reader-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.readerMode===mode);b.setAttribute('aria-pressed',b.dataset.readerMode===mode)})}
 else if(el.dataset.term){const b=data.blocks.find(b=>b.id===el.closest('.en-prose').dataset.block);showContext(b,data.terms[+el.dataset.term])}
 else if(el.dataset.focus){showContext(data.blocks.find(b=>b.id===el.dataset.focus))}
 else if(el.dataset.queue){if(!pending.includes(el.dataset.queue))pending.push(el.dataset.queue);const ok=save('photon-pending',pending);el.textContent='已加入待译清单';host.querySelector('[data-show-pending]').textContent='待译清单 '+pending.length;status(ok?'已记录这一段的翻译需求。':'未能持久保存，请导出待译清单。')}
 else if(el.hasAttribute('data-show-vocab'))listSaved('vocab');
 else if(el.hasAttribute('data-show-pending'))listSaved('pending');
 else if(el.dataset.returnBlock){const b=data.blocks.find(b=>b.id===el.dataset.returnBlock);close();if(b)navigate(el.dataset.returnUnit||unit.id,b.page,b.id)}
 else if(el.dataset.removeReader){const v=el.dataset.removeReader;if(v==='vocab')vocabulary.splice(+el.dataset.removeIndex,1);else pending.splice(+el.dataset.removeIndex,1);save(v==='vocab'?'photon-vocabulary':'photon-pending',v==='vocab'?vocabulary:pending);close();render();listSaved(v)}
 else if(el.dataset.exportReader){const isV=el.dataset.exportReader==='vocab';download(isV?'光知-英文词句本.json':'光知-待译原文.json',JSON.stringify({book:data.title,edition:data.edition,items:isV?vocabulary:pending.map(id=>data.blocks.find(b=>b.id===id))},null,2),'application/json;charset=utf-8')}
 else if(el.hasAttribute('data-close-reader'))close();
 else if(el.hasAttribute('data-reader-search'))searchDialog();
 else if(el.dataset.zoom){const src=window.PHOTONICS_IMAGES[el.dataset.zoom];if(src)dialog(`<h2>${el.dataset.zoom} · PDF ${page}</h2><img class="reader-large-image" src="${src}" alt="教材原图放大">`);else status('原图尚未加载，请稍后重试。')}
 else if(el.hasAttribute('data-reader-pdf'))openPdf();
 else if(el.hasAttribute('data-replace-pdf'))host.querySelector('#reader-pdf-file').click();
 else if(el.hasAttribute('data-next-unit')){const next=data.units[data.units.indexOf(unit)+1];if(next)navigate(next.id,next.start);else status('已经是中文目录最后一节。')}
 else if(el.hasAttribute('data-retry-images'))hydrateImages(renderToken);
});
host.addEventListener('mouseup',()=>{const selection=window.getSelection(),text=selection?.toString().trim();if(!text||text.length<2||text.length>600)return;const anchor=selection.anchorNode?.parentElement?.closest('.en-prose'),end=selection.focusNode?.parentElement?.closest('.en-prose');if(anchor&&anchor===end){const b=data.blocks.find(b=>b.id===anchor.dataset.block);showContext(b,null,text)}});
window.PhotonicsReader={start,stop};
})();
