(()=>{'use strict';
const D=window.PHYSICAL_DATA,$=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const units=new Map(D.units.map(u=>[u.id,u]));
const storageKey='physical-optics-study-v1';let memory={};try{memory=JSON.parse(localStorage.getItem(storageKey)||'{}')||{}}catch{}
let current=null,pages={main:1,liang:null},refId=null,layout='both',zoom=100;
function persist(){try{localStorage.setItem(storageKey,JSON.stringify(memory));return true}catch{return false}}
function record(){return memory[current.id]||(memory[current.id]={note:'',done:false})}
function stash(){if(!current)return;record().note=$('#note-text').value;record().pages={...pages};record().ref=refId;persist()}
function imagePath(book,n){return `physical/${book}/${String(n).padStart(4,'0')}.jpg`}
function printPage(book,n){const v=n+D.books[book].offset;return v>0?`书内 ${v} 页`:'前置页（无阿拉伯印刷页码）'}
function setOutline(closed){$('#workspace').classList.toggle('outline-closed',closed);$('#toggle-outline').textContent=closed?'展开目录':'收起目录';$('#toggle-outline').setAttribute('aria-expanded',String(!closed))}
function outline(){const query=$('#outline-query').value.trim();$('#outline-tree').innerHTML=D.chapters.map(ch=>{const matches=D.units.filter(u=>u.id.startsWith(ch.id+'.')&&(!query||(u.id+u.title+u.note).includes(query)));if(!matches.length)return '';return `<details ${query||current?.id.startsWith(ch.id+'.')?'open':''}><summary>第 ${ch.id} 章 ${esc(ch.title)}</summary>${matches.map(u=>`<button class="unit ${u.id===current?.id?'active':''}" data-topic="${u.id}">${esc(u.id+' '+u.title)}<small>${memory[u.id]?.done?'✓ 已学过 · ':''}${u.refs.length?u.refs.length+' 个参考小节':u.status}</small></button>`).join('')}</details>`}).join('')||'<p class="outline-foot">没有匹配的小节；可以使用“搜索两本书”检索正文。</p>'}
function chips(){ $('#reference-chips').innerHTML=current.refs.map(id=>`<button data-ref="${id}" class="${refId===id?'active':''}">${esc(id+' '+D.refs[id].title)}</button>`).join('') }
function bookHtml(book){const main=book==='main',n=pages[book],label=main?'授课主教材':'梁铨廷 · 第 5 版';if(!n)return `<section class="book liang"><div class="book-header"><h3>${label}</h3><p>本节没有直接对应的梁书章节</p></div><div class="empty-book"><h3>这一节，继续以主教材为准。</h3><p>${esc(current.note)}</p><label for="browse-reference">也可以自由浏览梁书（不视为课程对应）：</label><select id="browse-reference"><option value="">选择梁书章节</option>${Object.values(D.refs).map(r=>`<option value="${r.id}">${esc(r.id+' '+r.title)}</option>`).join('')}</select></div></section>`;
const ref=D.refs[refId],inRange=main?n>=current.start&&n<=current.end:!!ref&&n>=ref.start&&n<=ref.end,matched=main||current.refs.includes(refId);
const scope=main?`本节 PDF ${current.start}–${current.end} 页`:(ref?`${ref.id} ${ref.title} · PDF ${ref.start}–${ref.end} 页`:'梁书自由浏览');
return `<section class="book ${book}" aria-label="${label}"><div class="book-header"><h3>${label}</h3><p>${main?'《物理光学_教材.pdf》 · 工程光学第4版下篇':'《物理光学》第5版 · 梁铨廷'}</p><form class="page-controls" data-page-form="${book}"><button type="button" data-page-step="${book}" data-step="-1" ${n===1?'disabled':''} aria-label="${label}上一页">‹</button><label for="page-${book}">PDF</label><input id="page-${book}" type="number" min="1" max="${D.books[book].pages}" value="${n}" required aria-label="${label}PDF页码"><button type="submit">跳转</button><button type="button" data-page-step="${book}" data-step="1" ${n===D.books[book].pages?'disabled':''} aria-label="${label}下一页">›</button><span>${printPage(book,n)}</span><a href="physical/${book}.pdf#page=${n}" target="_blank" rel="noopener">原 PDF</a></form></div><div class="source-scope">${esc(scope)}${!inRange||!matched?' · 当前为自由翻阅，不代表本节直接对应':''} · 边界页可能含相邻小节</div><button class="page-image" data-zoom="${book}" aria-label="放大${label}第${n}页"><img src="${imagePath(book,n)}" alt="${label} PDF第${n}页，${printPage(book,n)}" decoding="async"></button><div class="image-caption">点击原页放大 · 独立翻页不会改变另一侧页码</div></section>`}
function renderBooks(){ $('#books').dataset.layout=layout;$('#books').innerHTML=bookHtml('main')+bookHtml('liang');$$('[data-page-form]').forEach(form=>form.onsubmit=e=>{e.preventDefault();const book=form.dataset.pageForm;goPage(book,Number($('#page-'+book).value))});const select=$('#browse-reference');if(select)select.onchange=()=>{if(select.value)chooseRef(select.value)};$$('.page-image img').forEach(img=>img.onerror=()=>{const p=document.createElement('p');p.className='empty-book';p.textContent='原页图片未加载，请确认已完整解压私密包，或点击上方“原 PDF”。';img.parentNode.replaceWith(p)}) }
function heading(){const ch=D.chapters.find(c=>current.id.startsWith(c.id+'.'));$('#chapter-name').textContent=`第 ${ch.id} 章 / ${ch.title}`;$('#topic-title').textContent=current.id+' '+current.title;$('#match-status').textContent=current.status;$('#mapping-note').textContent=current.note;$('#complete-topic').textContent=record().done?'✓ 已标记学过':'标记学过';const i=D.units.indexOf(current);$('#previous-topic').disabled=i===0;$('#next-topic').disabled=i===D.units.length-1;$('#topic-progress').textContent=`${i+1} / ${D.units.length} 小节 · 已学过 ${D.units.filter(u=>memory[u.id]?.done).length} 节`;chips()}
function route(){const id=location.hash.split('/')[1]||'11.1',next=units.get(id)||D.units.get?.('11.1')||D.units[0];if(current?.id===next.id)return;stash();current=next;const r=record();refId=current.refs[0]||null;pages={main:current.start,liang:refId?D.refs[refId].start:null};if(r.pages&&Number.isInteger(r.pages.main)&&r.pages.main>=1&&r.pages.main<=300){pages.main=r.pages.main;if(r.ref&&D.refs[r.ref]&&Number.isInteger(r.pages.liang)&&r.pages.liang>=1&&r.pages.liang<=385){refId=r.ref;pages.liang=r.pages.liang}}$('#note-text').value=r.note||'';$('#note-status').textContent='';$('#note-summary').textContent=r.note?'已有本节笔记':'收起时不占阅读区';heading();outline();renderBooks()}
function navigate(id){if(!units.has(id))return;if(location.hash===`#topic/${id}`)return;location.hash=`topic/${id}`}
function chooseRef(id){if(!D.refs[id])return;refId=id;pages.liang=D.refs[id].start;chips();renderBooks();stash()}
function goPage(book,n){if(!Number.isInteger(n)||n<1||n>D.books[book].pages)return;pages[book]=n;renderBooks();stash()}
function openZoom(book){const n=pages[book];if(!n)return;zoom=100;$('#zoom-image').style.width='100%';$('#zoom-image').src=imagePath(book,n);$('#image-title').textContent=`${D.books[book].label} · PDF ${n} / ${printPage(book,n)}`;$('#zoom-pdf').href=`physical/${book}.pdf#page=${n}`;$('#image-dialog').showModal()}
const aliases=[['倏逝波','倏逝场','隐失波','消逝波'],['可见度','对比度'],['夫琅和费','夫琅禾费'],['迈克耳逊','迈克耳孙'],['马赫-曾德','马赫-泽德'],['菲涅耳','菲涅尔'],['相位','位相']];
function variants(word){const group=aliases.find(g=>g.some(s=>word.includes(s)));if(!group)return [word];const from=group.find(s=>word.includes(s));return [...new Set([word,...group.map(s=>word.replace(from,s))])];}
const searchRecords=D.search.map(r=>({...r,normal:r.text.replace(/\s+/g,'').toLowerCase()}));
function search(){const raw=$('#book-query').value.trim(),words=raw.split(/\s+/).filter(Boolean).map(w=>variants(w.toLowerCase())),book=$('#search-book').value;if(!words.length)return;const hits=searchRecords.filter(r=>(book==='all'||r.book===book)&&words.every(ws=>ws.some(w=>r.normal.includes(w))));$('#search-status').textContent=`匹配 ${hits.length} 页，显示前 ${Math.min(hits.length,60)} 页。OCR 检索可能遗漏，请以原页核对。`;$('#search-results').innerHTML=hits.slice(0,60).map(r=>{const w=words.flat().find(w=>r.normal.includes(w)),at=Math.max(0,r.normal.indexOf(w)-35),sample=r.normal.slice(at,at+145),u=r.book==='main'?D.units.filter(u=>r.page>=u.start&&r.page<=u.end).at(-1):null;return `<button class="search-hit" data-search-book="${r.book}" data-search-page="${r.page}" ${u?`data-search-topic="${u.id}"`:''}><b>${r.book==='main'?'主教材':'梁书'} · PDF ${r.page} / ${printPage(r.book,r.page)}${u?' · '+esc(u.title):''}</b><small>${esc(sample)}${sample.length===145?'…':''}</small></button>`}).join('')||'<p>未找到匹配内容。试试更短的关键词。</p>'}
function exportNote(){stash();const text=`# ${current.id} ${current.title}\n\n主教材：${D.books.main.filename}，PDF ${pages.main}，${printPage('main',pages.main)}。\n梁书：${pages.liang?D.books.liang.filename+'，PDF '+pages.liang+'，'+printPage('liang',pages.liang):'无直接对应'}。\n\n对应说明：${current.note}\n\n## 我的笔记\n\n${record().note||'（尚未填写）'}\n`;const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`物理光学-${current.id}-双书笔记.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;if(el.dataset.topic)navigate(el.dataset.topic);if(el.dataset.ref)chooseRef(el.dataset.ref);if(el.dataset.pageStep)goPage(el.dataset.pageStep,pages[el.dataset.pageStep]+Number(el.dataset.step));if(el.dataset.zoom)openZoom(el.dataset.zoom);if(el.dataset.layout){layout=el.dataset.layout;$$('[data-layout]').filter(b=>b.tagName==='BUTTON').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layout===layout)));$('#books').dataset.layout=layout}if(el.dataset.close)$('#'+el.dataset.close).close();if(el.dataset.searchBook){const book=el.dataset.searchBook,page=Number(el.dataset.searchPage),id=el.dataset.searchTopic;$('#search-dialog').close();if(id&&id!==current.id){stash();location.hash=`topic/${id}`;current=null;route()}goPage(book,page)}});
$('#outline-query').oninput=outline;$('#close-outline').onclick=()=>setOutline(true);$('#toggle-outline').onclick=()=>setOutline(!$('#workspace').classList.contains('outline-closed'));$('#complete-topic').onclick=()=>{record().done=!record().done;persist();heading();outline()};$('#previous-topic').onclick=()=>navigate(D.units[D.units.indexOf(current)-1]?.id);$('#next-topic').onclick=()=>navigate(D.units[D.units.indexOf(current)+1]?.id);$('#open-search').onclick=()=>{$('#search-dialog').showModal();$('#book-query').focus()};$('#search-form').onsubmit=e=>{e.preventDefault();search()};$('#save-note').onclick=()=>{record().note=$('#note-text').value;const ok=persist();$('#note-status').textContent=ok?'已保存到此浏览器':'浏览器未允许保存，请导出笔记备份';$('#note-summary').textContent=record().note?'已有本节笔记':'收起时不占阅读区'};$('#note-text').oninput=()=>{record().note=$('#note-text').value;$('#note-status').textContent='未保存'};$('#export-note').onclick=e=>{e.preventDefault();exportNote()};$('#zoom-in').onclick=()=>{zoom=Math.min(250,zoom+25);$('#zoom-image').style.width=zoom+'%'};$('#zoom-out').onclick=()=>{zoom=Math.max(50,zoom-25);$('#zoom-image').style.width=zoom+'%'};window.addEventListener('hashchange',route);window.addEventListener('beforeunload',stash);route();
})();
