/* Offline course retrieval and deterministic optical visualization. No remote model. */
(()=>{'use strict';
const q=s=>document.querySelector(s),all=s=>Array.from(document.querySelectorAll(s)),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const records=COURSE_LIBRARY.records,available=new Set(['intro-2',...['42','45','63','65','67','71','92'].map(n=>'waves-'+n)]);
const aliases=[['高斯光束','高斯','gaussian','束腰','束半径'],['稳定腔','谐振腔','稳定性','resonator','稳定条件'],['量子效率','quantum efficiency'],['ABCD','abcd','变换矩阵'],['电光调制','电光效应']];
function retrieve(query,filter='all'){
 const queryLower=query.trim().toLowerCase();if(!queryLower)return [];
 const words=queryLower.split(/[\s，,。？?]+/).filter(Boolean),group=aliases.find(g=>g.some(w=>queryLower.includes(w.toLowerCase())));
 const expanded=group?group.map(w=>w.toLowerCase()):[];
 return records.filter(r=>filter==='all'||r.kind===filter).map(r=>{const body=r.text.toLowerCase(),title=r.title.toLowerCase();let score=body.includes(queryLower)?30:0;for(const w of words){if(body.includes(w))score+=8;if(title.includes(w))score+=15}for(const w of expanded)if(body.includes(w))score+=3;return {r,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).map(x=>x.r);
}
function snippet(r,query,max=160){const s=r.preview||r.text;let at=s.toLowerCase().indexOf(query.toLowerCase());if(at<0)at=0;return (at>35?'…':'')+s.slice(Math.max(0,at-35),Math.max(0,at-35)+max)+(s.length>max?'…':'')}
function showPage(id){if(!available.has(id))return;const r=records.find(x=>x.id===id);q('#slide-dialog-title').textContent=r.location;q('#slide-dialog-image').src='assets/slides/'+id+'.png';q('#slide-dialog-image').alt=r.location+'原页';q('#slide-dialog').showModal()}
q('#close-slide').onclick=()=>q('#slide-dialog').close();
function readRecord(id){const r=records.find(x=>x.id===id);if(!r)return;all('.library-hit').forEach(b=>b.classList.toggle('active',b.dataset.record===id));q('#library-reader').innerHTML=`<div class="section-kicker">${r.kind==='book'?'教材原文 / MARKDOWN':'课程原文 / PPT'}</div><h2>${esc(r.title)}</h2><div class="reader-meta">${esc(r.location)}</div>${available.has(id)?`<button class="slide-card" data-page="${id}" aria-label="放大原页"><img class="reader-page" src="assets/slides/${id}.png" alt="${esc(r.location)}"></button>`:''}<p>${r.kind==='book'?'以下为原整理稿，保留公式与上下文；OCR 符号可能有误，请结合课件原页核对。':available.has(id)?'点击图片放大核对公式。以下为同页提取文字。':'本页提供文字索引；演示精选页另有原页图片。'}</p>${r.kind==='book'?`<div class="reader-prose">${esc(r.preview).replace(/^#{1,3}\s*/,'')}</div><details class="raw-details"><summary>展开完整 Markdown 与公式源码</summary><pre class="source-raw">${esc(r.text)}</pre></details>`:`<pre class="source-raw">${esc(r.text)}</pre>`}`;}
function searchLibrary(query,filter=q('#library-filter').value){q('#library-query').value=query;const hits=retrieve(query,filter);q('#library-result-count').textContent=query.trim()?`${hits.length} 条相关记录 · 显示前 ${Math.min(12,hits.length)} 条 · 词项匹配`:'输入关键词，搜索自己的课程资料';q('#library-results').innerHTML=hits.slice(0,12).map(r=>`<button class="library-hit" data-record="${r.id}"><small>${r.kind==='book'?'教材 MD':'课程 PPT'} · ${esc(r.location)}</small><h3>${esc(r.title)}</h3><p>${esc(snippet(r,query))}</p></button>`).join('')||'<div class="panel" style="padding:24px"><h3>没有找到对应原文</h3><p>试试更短的课程关键词。本地检索不会为缺失的资料编造回答。</p></div>';if(hits.length)readRecord(hits[0].id);else q('#library-reader').innerHTML='<h2>等待有依据的结果</h2><p>检索当前导入的教材和课件，不扩展生成内容。</p>';}
q('#library-stats').innerHTML=`<div><b>${COURSE_LIBRARY.stats.bookChunks}</b><span>教材原文片段</span></div><div><b>${COURSE_LIBRARY.stats.slidePages}</b><span>课程 PPT 页索引</span></div><div><b>3</b><span>已接入课程资料</span></div>`;
q('#library-form').onsubmit=e=>{e.preventDefault();searchLibrary(q('#library-query').value)};q('#library-filter').onchange=()=>searchLibrary(q('#library-query').value);
document.addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(page)showPage(page.dataset.page);const hit=e.target.closest('[data-record]');if(hit)readRecord(hit.dataset.record);const search=e.target.closest('[data-search]');if(search){showView('library');q('#library-filter').value='all';searchLibrary(search.dataset.search)}const raw=e.target.closest('[data-open-record]');if(raw){showView('library');q('#library-filter').value='book';searchLibrary(story==='gaussian'?'束半径':'稳定条件','book');readRecord(raw.dataset.openRecord)}});
const cases={gaussian:{label:'GAUSSIAN BEAM / 高斯光束',pages:[65,67],query:'束半径',heading:'把“聚焦”与“发散”放在同一张图里',slideText:'第 65 页给出束半径与发散角，第 67 页引出焦深。拖动左侧束腰，观察它们如何一起变化。',note:'固定 λ = 633 nm；W₀ 是强度降至轴上 1/e² 处的半径。',question:'束腰减半后，发散角和焦深分别怎么变？',conclusion:'点击“50 μm”作比较：远场半发散角变为 2 倍，焦深变为 1/4。',formula:'θ₀ = λ / (πW₀)<br>2z₀ = 2πW₀² / λ',explain:'光束的横向局限与传播方向的分布相联系。束腰越小，远离束腰后的扩展越快；保持近似平行的轴向范围也越短。',answer:'λ 不变时，θ₀ ∝ 1/W₀，所以束腰减半，发散角加倍；焦深 2z₀ ∝ W₀²，因此缩为原来的 1/4。不要把半发散角与全发散角混用。'},cavity:{label:'RESONATOR / 谐振腔稳定性',pages:[42,45],query:'稳定条件',heading:'先统一曲率半径的正负号',slideText:'第 42 页规定凹面镜 R < 0；第 45 页用 g = 1 + d/R。符号约定必须连同公式一起读。',note:'本演示沿用课件约定：R₁ = −500 mm，R₂ = −1000 mm。',question:'腔长从 250 mm 改成 750 mm，光线还会保持有界吗？',conclusion:'改变腔长，比较 g₁g₂ 与近轴光线轨迹；再去原页确认符号约定。',formula:'g₁ = 1 + d/R₁，g₂ = 1 + d/R₂<br>稳定区：0 < g₁g₂ < 1',explain:'在这份课件里凹面镜半径取负值，所以公式用加号。如果另一份资料把同一凹面镜半径的大小记为正数，就会写成减号。先转换约定，才能比较结果。',answer:'250 mm 时 g₁g₂ = 0.375，处于稳定区；750 mm 时为 −0.125，处于不稳定区。端点 0 和 1 需单独讨论，不能由有限条光线直接推断所有初始条件都稳定。'}};
let story='gaussian',tab='slides',paused=matchMedia('(prefers-reduced-motion: reduce)').matches,tick=0;
function evidence(){const c=cases[story];all('[data-evidence]').forEach(b=>b.classList.toggle('active',b.dataset.evidence===tab));let html='';if(tab==='slides')html=`<h3>${c.heading}</h3><p>${c.slideText}</p><div class="slide-thumbs">${c.pages.map(p=>`<button class="slide-card" data-page="waves-${p}"><img src="assets/slides/waves-${p}.png" alt="课程 PPT 第 ${p} 页"><span>PDF 第 ${p} 页 · 点击放大 ↗</span></button>`).join('')}</div><div class="evidence-note"><b>沿用课程约定</b><br>${c.note}</div>`;
 if(tab==='book'){let hits=retrieve(c.query,'book');const preferred=hits.filter(r=>story==='gaussian'?r.start>=1150&&r.start<1300:r.start>=990&&r.start<1100);if(preferred.length)hits=preferred;html=`<h3>在你整理的教材里找到依据</h3><p>检索词：${c.query} · 从 ${COURSE_LIBRARY.stats.bookChunks} 个真实片段中匹配</p>${hits.slice(0,2).map(r=>`<div class="source-match"><small>${esc(r.location)}</small><p>${esc(snippet(r,c.query,130))}</p><button data-open-record="${r.id}">阅读完整原文 →</button></div>`).join('')}<button class="answer-link" data-search="${story==='gaussian'?'高斯光束':'稳定腔'}">打开完整课程资料库 ↗</button>`;}
 if(tab==='explain')html=`<div class="section-kicker">备好的讲解示例 · 非实时生成</div><h3 style="margin-top:10px">${story==='gaussian'?'用一次操作，检验一个解释':'公式之前，先核对定义'}</h3><p>${c.explain}</p><div class="evidence-equation">${c.formula}</div><details class="reveal-box"><summary>课堂追问：先预测，再展开答案</summary><p>${c.question}</p><p>${c.answer}</p></details><button class="answer-link" data-full-lab="${story}">进入完整实验台 →</button>`;
 q('#studio-evidence').innerHTML=html;q('#studio-next').textContent=tab==='slides'?'下一步：查教材 →':tab==='book'?'下一步：验证理解 →':'切换另一个案例 →';}
function metric(label,value,unit=''){return `<div><small>${label}</small><b>${value}</b> <em>${unit}</em></div>`}
function update(){const v=+q('#studio-range').value;if(story==='gaussian'){const g=Optics.gaussian(v,633,0);q('#studio-range-output').textContent=v+' μm';q('#studio-values').innerHTML=metric('束腰半径 W₀',v,'μm')+metric('瑞利长度 z₀',g.zr.toFixed(1),'mm')+metric('半发散角 θ₀',g.divergence.toFixed(2),'mrad')+metric('焦深 2z₀',(2*g.zr).toFixed(1),'mm');}else{const c=Optics.cavity(v,-500,-1000);q('#studio-range-output').textContent=v+' mm';q('#studio-values').innerHTML=metric('腔长 d',v,'mm')+metric('g₁',c.g1.toFixed(2))+metric('g₂',c.g2.toFixed(2))+metric('g₁g₂',c.p.toFixed(3));}all('[data-studio-value]').forEach(b=>b.classList.toggle('active',+b.dataset.studioValue===v));draw();}
function choose(id){story=id;const c=cases[id];all('[data-story]').forEach(b=>b.classList.toggle('active',b.dataset.story===id));q('#visual-label').textContent=c.label;q('#studio-control-label').innerHTML=`${id==='gaussian'?'束腰半径 W₀':'两镜间距 d'} <output id="studio-range-output"></output>`;const range=q('#studio-range');range.min=id==='gaussian'?50:100;range.max=id==='gaussian'?200:1500;range.step=id==='gaussian'?1:10;range.value=id==='gaussian'?100:250;q('#studio-presets').innerHTML=(id==='gaussian'?[[100,'100 μm · 基准'],[50,'50 μm · 束腰减半'],[200,'200 μm · 束腰加倍']]:[[250,'250 · 稳定'],[750,'750 · 不稳定'],[1250,'1250 · 稳定'],[1500,'1500 · 临界']]).map(([v,t])=>`<button data-studio-value="${v}">${t}</button>`).join('');q('#studio-model-note').textContent=id==='gaussian'?'基模高斯光束，λ = 633 nm；横纵比例不同。边界为 1/e² 强度包络；流动纹理仅示意传播，非全波仿真。':'近轴几何光学，固定初始光线，最多 24 次传播；超出绘图区即停止。有限轨迹仅作示意，稳定性由 g 参数判定。';q('#studio-question').textContent=c.question;q('#studio-conclusion').textContent=c.conclusion;tab='slides';evidence();update();}
all('[data-story]').forEach(b=>b.onclick=()=>choose(b.dataset.story));all('[data-evidence]').forEach(b=>b.onclick=()=>{tab=b.dataset.evidence;evidence()});q('#studio-next').onclick=()=>{if(tab==='explain')choose(story==='gaussian'?'cavity':'gaussian');else{tab=tab==='slides'?'book':'explain';evidence()}};q('#studio-range').oninput=update;
q('#studio-pause').onclick=()=>{paused=!paused;q('#studio-pause').textContent=paused?'▷ 播放动效':'Ⅱ 暂停动效';};if(paused)q('#studio-pause').textContent='▷ 播放动效';
document.addEventListener('click',e=>{const preset=e.target.closest('[data-studio-value]');if(preset){q('#studio-range').value=preset.dataset.studioValue;update()}const lab=e.target.closest('[data-full-lab]');if(lab)window.openExperiment(lab.dataset.fullLab)});
const canvas=q('#studio-canvas'),ctx=canvas.getContext('2d');
function line(x1,y1,x2,y2,color,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function text(s,x,y,color='#96b3bf',size=19,align='left'){ctx.font=`${size}px "Microsoft YaHei",sans-serif`;ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(s,x,y)}
function draw(){ctx.clearRect(0,0,1100,520);const bg=ctx.createRadialGradient(550,235,30,550,235,620);bg.addColorStop(0,'#163946');bg.addColorStop(1,'#0b202d');ctx.fillStyle=bg;ctx.fillRect(0,0,1100,520);for(let x=50;x<1100;x+=50)line(x,40,x,450,'#9fd5ce08');for(let y=50;y<470;y+=50)line(45,y,1055,y,'#9fd5ce08');ctx.setLineDash([5,9]);line(65,250,1035,250,'#81aba944');ctx.setLineDash([]);const v=+q('#studio-range').value;
 if(story==='gaussian'){
 const g=Optics.gaussian(v,633,0),width=x=>Optics.gaussian(v,633,(x-550)/2.35).w*220;
 for(let layer=12;layer>=1;layer--){const f=layer/12;ctx.beginPath();for(let x=80;x<=1020;x+=4){const y=250-width(x)*f;x===80?ctx.moveTo(x,y):ctx.lineTo(x,y)}for(let x=1020;x>=80;x-=4)ctx.lineTo(x,250+width(x)*f);ctx.closePath();ctx.fillStyle=`rgba(71,235,173,${.022+(1-f)*.025})`;ctx.fill()}
 for(const sign of [-1,1]){ctx.beginPath();for(let x=80;x<=1020;x+=3){const y=250+sign*width(x);x===80?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.strokeStyle='#8bedbf';ctx.lineWidth=2;ctx.stroke()}
 ctx.save();ctx.shadowColor='#8af2c4';ctx.shadowBlur=13;for(let i=0;i<32;i++){const x=80+((i*31+tick*90)%940),f=Math.sin(i*17.9)*.72,y=250+f*width(x);ctx.fillStyle='#baf9da';ctx.globalAlpha=.25+(.6*(1-Math.abs(f)));ctx.beginPath();ctx.ellipse(x,y,3.5,1.7,0,0,Math.PI*2);ctx.fill()}ctx.restore();
 const zx=g.zr*2.35;ctx.setLineDash([4,7]);line(550-zx,100,550-zx,400,'#dfbf7577');line(550+zx,100,550+zx,400,'#dfbf7577');ctx.setLineDash([]);line(550,235-width(550),550,265+width(550),'#e5f4ed',2);text('W₀',564,235-width(550),'#ddf6e8',22);line(550-zx,405,550+zx,405,'#e8c883',2);line(550-zx,398,550-zx,412,'#e8c883',2);line(550+zx,398,550+zx,412,'#e8c883',2);text('焦深 2z₀ = '+(2*g.zr).toFixed(1)+' mm',550,440,'#e9cb8a',21,'center');text('−200 mm',80,480,'#71949f',16);text('束腰 z = 0',550,480,'#71949f',16,'center');text('+200 mm',1020,480,'#71949f',16,'right');text(v===50?'束腰 × ½    发散角 × 2    焦深 × ¼':'收紧束腰，观察光束两端如何展开',550,60,'#bfe4d5',21,'center');
 }else{
 const c=Optics.cavity(v,-500,-1000),color=c.state==='不稳定'?'#f1b576':'#9bebbd';text(c.state+'  /  g₁g₂ = '+c.p.toFixed(3),550,62,color,26,'center');const points=[[170,258]];let y=2,theta=.004;for(let i=0;i<24;i++){y+=v*theta;const x=i%2?170:930;if(Math.abs(y)>43){const prev=points[points.length-1],destY=250+y*4,clampY=y>0?422:78,ratio=(clampY-prev[1])/(destY-prev[1]);points.push([prev[0]+(x-prev[0])*ratio,clampY]);break}points.push([x,250+y*4]);theta+=2*y/(i%2?-500:-1000)}
 ctx.save();ctx.strokeStyle=color;ctx.shadowColor=color;ctx.shadowBlur=8;ctx.lineWidth=1.5;ctx.globalAlpha=.65;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();ctx.restore();for(const x of [170,930]){ctx.strokeStyle='#b4d9e4';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(x,115);ctx.quadraticCurveTo(x+(x===170?-30:30),250,x,385);ctx.stroke();line(x,386,x,420,'#476270',5);line(x-34,420,x+34,420,'#476270',6)}const f=(tick*1.4)%(points.length-1),i=Math.floor(f),a=points[i],b=points[i+1];if(a&&b){ctx.save();ctx.shadowBlur=22;ctx.shadowColor=color;ctx.fillStyle='#f7ffe7';ctx.beginPath();ctx.arc(a[0]+(b[0]-a[0])*(f-i),a[1]+(b[1]-a[1])*(f-i),5,0,Math.PI*2);ctx.fill();ctx.restore()}text('R₁ = −500 mm',170,465,'#a1bac5',18,'center');text('R₂ = −1000 mm',930,465,'#a1bac5',18,'center');text('d = '+v+' mm',550,465,color,21,'center');text('镜距图形位置固定，参数参与光线传播计算',550,500,'#688994',14,'center');
 }}
let last=0;function frame(time){const dt=last?Math.min((time-last)/1000,.05):0;last=time;if(!q('#studio').hidden&&!paused){tick+=dt;draw()}requestAnimationFrame(frame)}
window.searchCourseLibrary=query=>{showView('library');q('#library-filter').value='all';searchLibrary(query,'all')};
searchLibrary('高斯光束');choose('gaussian');requestAnimationFrame(frame);
})();
